export const AUTO_GENERATED_START_MARKER = "<!-- AUTO_GENERATED_START -->";
export const AUTO_GENERATED_END_MARKER = "<!-- AUTO_GENERATED_END -->";

export type HybridMergeStatus =
  | "replaced-existing-block"
  | "appended-new-block"
  | "missing-start-marker"
  | "missing-end-marker"
  | "malformed-marker-order"
  | "empty-generated-content";

export interface HybridMergeResult {
  status: HybridMergeStatus;
  mergedMarkdown: string;
  diagnostics: string[];
  preservedUserContent: boolean;
  changed: boolean;
}

/**
 * Ensures the generated markdown is properly wrapped with start and end markers.
 */
export function buildAutoGeneratedBlock(generatedMarkdown: string): string {
  if (hasAutoGeneratedBlock(generatedMarkdown)) {
    return generatedMarkdown.trim();
  }
  return `${AUTO_GENERATED_START_MARKER}\n${generatedMarkdown.trim()}\n${AUTO_GENERATED_END_MARKER}`;
}

/**
 * Checks if both start and end markers exist in the markdown.
 */
export function hasAutoGeneratedBlock(markdown: string): boolean {
  return markdown.includes(AUTO_GENERATED_START_MARKER) && markdown.includes(AUTO_GENERATED_END_MARKER);
}

/**
 * Extracts the auto-generated block (including markers) if it exists.
 */
export function extractAutoGeneratedBlock(markdown: string): string | null {
  const start = markdown.indexOf(AUTO_GENERATED_START_MARKER);
  const end = markdown.indexOf(AUTO_GENERATED_END_MARKER);
  if (start === -1 || end === -1 || start > end) {
    return null;
  }
  return markdown.substring(start, end + AUTO_GENERATED_END_MARKER.length);
}

/**
 * Strips potentially unsafe metadata or secrets from the markdown.
 */
export function stripUnsafePreviewMetadata(markdown: string): string {
  return markdown
    .split("\n")
    .filter(line => {
      const lower = line.toLowerCase();
      return !(
        lower.includes("access_token") ||
        lower.includes("refresh_token") ||
        lower.includes("client_secret") ||
        lower.includes("bearer ") ||
        lower.includes("api_key")
      );
    })
    .join("\n");
}

/**
 * Merges the new generated block into an existing index.md markdown string.
 * This function preserves all user-authored content outside the markers.
 */
export function mergeIndexMdAutoGeneratedBlock(
  existingMarkdown: string,
  generatedMarkdown: string,
  options?: { allowAppendIfMissing?: boolean }
): HybridMergeResult {
  const normalizedGenerated = stripUnsafePreviewMetadata(generatedMarkdown);

  if (!normalizedGenerated || normalizedGenerated.trim() === "") {
    return {
      status: "empty-generated-content",
      mergedMarkdown: existingMarkdown,
      diagnostics: ["生成されたコンテンツが空か、無効なフィールドが含まれていました。"],
      preservedUserContent: true,
      changed: false,
    };
  }

  const startIdx = existingMarkdown.indexOf(AUTO_GENERATED_START_MARKER);
  const endIdx = existingMarkdown.indexOf(AUTO_GENERATED_END_MARKER);

  const blockToInsert = buildAutoGeneratedBlock(normalizedGenerated);

  // Case 1: Both markers are missing or only one is missing
  if (startIdx === -1 && endIdx === -1) {
    if (options?.allowAppendIfMissing) {
      const separator = existingMarkdown.length > 0 && !existingMarkdown.endsWith("\n") ? "\n\n" : "";
      const merged = existingMarkdown + separator + blockToInsert;
      return {
        status: "appended-new-block",
        mergedMarkdown: merged,
        diagnostics: ["既存のマーカーが見つからなかったため、ファイルの末尾に新規ブロックを追記しました。"],
        preservedUserContent: true,
        changed: merged !== existingMarkdown,
      };
    } else {
      return {
        status: "missing-start-marker",
        mergedMarkdown: existingMarkdown,
        diagnostics: ["開始および終了マーカーがファイル内に存在しません。書き換えを中止しました。"],
        preservedUserContent: true,
        changed: false,
      };
    }
  }

  if (startIdx !== -1 && endIdx === -1) {
    return {
      status: "missing-end-marker",
      mergedMarkdown: existingMarkdown,
      diagnostics: ["開始マーカーは存在しますが、終了マーカーが見つかりません。"],
      preservedUserContent: true,
      changed: false,
    };
  }

  if (startIdx === -1 && endIdx !== -1) {
    return {
      status: "missing-start-marker",
      mergedMarkdown: existingMarkdown,
      diagnostics: ["終了マーカーは存在しますが、開始マーカーが見つかりません。"],
      preservedUserContent: true,
      changed: false,
    };
  }

  if (startIdx > endIdx) {
    return {
      status: "malformed-marker-order",
      mergedMarkdown: existingMarkdown,
      diagnostics: ["マーカーの順序が不正です（開始マーカーが終了マーカーより後にあります）。"],
      preservedUserContent: true,
      changed: false,
    };
  }

  // Case 2: Both markers exist and are ordered correctly. Replace only the block between markers.
  const before = existingMarkdown.substring(0, startIdx);
  const after = existingMarkdown.substring(endIdx + AUTO_GENERATED_END_MARKER.length);
  const merged = before + blockToInsert + after;

  return {
    status: "replaced-existing-block",
    mergedMarkdown: merged,
    diagnostics: [],
    preservedUserContent: true,
    changed: merged !== existingMarkdown,
  };
}
