import { test } from "node:test";
import assert from "node:assert";
import { buildAutoGeneratedIndexSection, INDEX_MD_FORMAT_VERSION } from "./indexMdFormat.js";
import { PROMPT_SPEC_VERSION } from "./promptSpecs.js";

test("buildAutoGeneratedIndexSection constructs correct format", () => {
  const result = buildAutoGeneratedIndexSection({
    folderSummary: "This is a summary",
    mdFilesText: "- [file1.txt](link)",
    mdSubdirsText: "- [sub1/](link)",
    nowIso: "2026-06-24T00:00:00.000Z"
  });

  assert.ok(result.includes("## AI Summary"));
  assert.ok(result.includes("## Files"));
  assert.ok(result.includes("## Subdirectories"));
  assert.ok(result.includes("This is a summary"));
  assert.ok(result.includes("- [file1.txt](link)"));
  assert.ok(result.includes("- [sub1/](link)"));
  assert.ok(result.includes("2026-06-24T00:00:00.000Z"));
  assert.ok(result.includes(`formatVersion: ${INDEX_MD_FORMAT_VERSION}`));
  assert.ok(result.includes(`promptSpecVersion: ${PROMPT_SPEC_VERSION}`));
});

test("buildAutoGeneratedIndexSection handles empty files and subdirs", () => {
  const result = buildAutoGeneratedIndexSection({
    folderSummary: "Empty folder",
    mdFilesText: "",
    mdSubdirsText: "",
    nowIso: "2026-06-24T00:00:00.000Z"
  });

  assert.ok(result.includes("このディレクトリには直接配置されたファイルが存在しません。"));
  assert.ok(result.includes("このディレクトリにはサブディレクトリがありません。"));
});

test("buildAutoGeneratedIndexSection does not emit undefined or null", () => {
  const result = buildAutoGeneratedIndexSection({
    folderSummary: "",
    mdFilesText: "",
    mdSubdirsText: "",
    nowIso: "2026-06-24T00:00:00.000Z"
  });

  assert.ok(!result.includes("undefined"));
  assert.ok(!result.includes("null"));
});

test("buildAutoGeneratedIndexSection deterministic output for fixed nowIso", () => {
  const input = {
    folderSummary: "Summary",
    mdFilesText: "Files",
    mdSubdirsText: "Subdirs",
    nowIso: "2026-01-01T12:00:00.000Z"
  };

  const result1 = buildAutoGeneratedIndexSection(input);
  const result2 = buildAutoGeneratedIndexSection(input);

  assert.strictEqual(result1, result2);
});
