import { PROMPT_SPEC_VERSION } from "./promptSpecs.js";

export const INDEX_MD_FORMAT_VERSION = "1.0.0";

export interface IndexMdInput {
  folderSummary: string;
  mdFilesText: string;
  mdSubdirsText: string;
  nowIso: string;
}

export function buildAutoGeneratedIndexSection(input: IndexMdInput): string {
  return `
## AI Summary (生成日時: ${input.nowIso})
${input.folderSummary}

## Files
${input.mdFilesText || "*このディレクトリには直接配置されたファイルが存在しません。*"}

## Subdirectories
${input.mdSubdirsText || "*このディレクトリにはサブディレクトリがありません。*"}

<!-- formatVersion: ${INDEX_MD_FORMAT_VERSION}, promptSpecVersion: ${PROMPT_SPEC_VERSION} -->
`;
}
