import { mergeIndexMdAutoGeneratedBlock, HybridMergeStatus } from "./indexMdHybridMerge";

export type IndexMdPreflightStatus =
  | "existing-index-found"
  | "missing-index"
  | "multiple-index-candidates"
  | "read-error"
  | "merge-ready"
  | "merge-blocked";

export interface IndexMdCandidate {
  fileId: string;
  fileName: string;
  mimeType?: string;
  modifiedTime?: string;
  parentId?: string;
}

export interface IndexMdPreflightResult {
  status: IndexMdPreflightStatus;
  diagnostics: string[];
  candidate?: IndexMdCandidate;
  existingMarkdown?: string;
  generatedMarkdown: string;
  mergedMarkdown?: string;
  mergeStatus?: HybridMergeStatus | string;
  changed?: boolean;
  preservedUserContent?: boolean;
  canProceedToFutureWrite: boolean;
}

export interface PreflightInput {
  candidates: IndexMdCandidate[];
  existingMarkdown: string | null;
  generatedMarkdown: string;
  allowAppendIfMissing?: boolean;
}

/**
 * Pure helper to analyze the index.md candidates and run a dry-run merge
 * if an existing file is successfully read.
 */
export function runIndexMdPreflight(input: PreflightInput): IndexMdPreflightResult {
  const { candidates, existingMarkdown, generatedMarkdown, allowAppendIfMissing } = input;

  if (candidates.length === 0) {
    return {
      status: "missing-index",
      diagnostics: ["既存の index.md が見つかりませんでした。新規作成候補としてプレビューします。"],
      generatedMarkdown,
      mergedMarkdown: generatedMarkdown, // In new file case, merged is just generated
      canProceedToFutureWrite: true,
      changed: true,
    };
  }

  if (candidates.length > 1) {
    return {
      status: "multiple-index-candidates",
      diagnostics: ["同じフォルダ内に複数の index.md 候補が存在します。自動マージはブロックされます。"],
      generatedMarkdown,
      canProceedToFutureWrite: false,
    };
  }

  const candidate = candidates[0];

  if (existingMarkdown === null) {
    return {
      status: "read-error",
      diagnostics: ["既存の index.md を読み取れませんでした。"],
      candidate,
      generatedMarkdown,
      canProceedToFutureWrite: false,
    };
  }

  // We have exactly one candidate and its content. Run merge.
  const mergeResult = mergeIndexMdAutoGeneratedBlock(existingMarkdown, generatedMarkdown, {
    allowAppendIfMissing,
  });

  const canProceed =
    mergeResult.status === "replaced-existing-block" ||
    mergeResult.status === "appended-new-block";

  return {
    status: canProceed ? "merge-ready" : "merge-blocked",
    diagnostics: mergeResult.diagnostics,
    candidate,
    existingMarkdown,
    generatedMarkdown,
    mergedMarkdown: mergeResult.mergedMarkdown,
    mergeStatus: mergeResult.status,
    changed: mergeResult.changed,
    preservedUserContent: mergeResult.preservedUserContent,
    canProceedToFutureWrite: canProceed,
  };
}
