import test, { describe } from "node:test";
import assert from "node:assert";
import {
  mergeIndexMdAutoGeneratedBlock,
  buildAutoGeneratedBlock,
  hasAutoGeneratedBlock,
  extractAutoGeneratedBlock,
  stripUnsafePreviewMetadata,
  AUTO_GENERATED_START_MARKER,
  AUTO_GENERATED_END_MARKER
} from "./indexMdHybridMerge";

describe("index.md hybrid merge helper", () => {
  const sampleGenerated = "## AI Summary\nThis is a newly generated AI summary.";
  const sampleGeneratedWithMarkers = `${AUTO_GENERATED_START_MARKER}\n## AI Summary\nThis is a newly generated AI summary.\n${AUTO_GENERATED_END_MARKER}`;

  test("buildAutoGeneratedBlock wraps content correctly or preserves if already wrapped", () => {
    const block1 = buildAutoGeneratedBlock(sampleGenerated);
    assert.ok(block1.startsWith(AUTO_GENERATED_START_MARKER));
    assert.ok(block1.endsWith(AUTO_GENERATED_END_MARKER));

    const block2 = buildAutoGeneratedBlock(sampleGeneratedWithMarkers);
    assert.strictEqual(block2, sampleGeneratedWithMarkers);
  });

  test("hasAutoGeneratedBlock and extractAutoGeneratedBlock verify presence and extract correctly", () => {
    assert.strictEqual(hasAutoGeneratedBlock("hello world"), false);
    assert.strictEqual(hasAutoGeneratedBlock(sampleGeneratedWithMarkers), true);

    assert.strictEqual(extractAutoGeneratedBlock("hello world"), null);
    const extracted = extractAutoGeneratedBlock(`Intro\n${sampleGeneratedWithMarkers}\nOutro`);
    assert.strictEqual(extracted, sampleGeneratedWithMarkers);
  });

  test("stripUnsafePreviewMetadata filters secret tokens and credentials perfectly", () => {
    const raw = "Line 1\naccess_token: SECRET_TOKEN\nrefresh_token=ANOTHER_SECRET\nLine 4\napi_key: FOO";
    const cleaned = stripUnsafePreviewMetadata(raw);
    assert.ok(!cleaned.includes("access_token"));
    assert.ok(!cleaned.includes("refresh_token"));
    assert.ok(!cleaned.includes("api_key"));
    assert.ok(cleaned.includes("Line 1"));
    assert.ok(cleaned.includes("Line 4"));
  });

  test("replaces existing auto-generated block and preserves user notes before and after", () => {
    const existing = `# My Project Notes\nThis is human-written intro.\n\n${AUTO_GENERATED_START_MARKER}\nOld summary here\n${AUTO_GENERATED_END_MARKER}\n\n## Human Section\nMore human comments here.`;
    
    const result = mergeIndexMdAutoGeneratedBlock(existing, sampleGenerated);
    
    assert.strictEqual(result.status, "replaced-existing-block");
    assert.ok(result.mergedMarkdown.includes("# My Project Notes"));
    assert.ok(result.mergedMarkdown.includes("## Human Section"));
    assert.ok(result.mergedMarkdown.includes("This is a newly generated AI summary."));
    assert.ok(!result.mergedMarkdown.includes("Old summary here"));
    assert.strictEqual(result.preservedUserContent, true);
    assert.strictEqual(result.changed, true);
    assert.strictEqual(result.diagnostics.length, 0);
  });

  test("appends block only when allowAppendIfMissing is true", () => {
    const existing = "# Existing manual file\nNo markers here.";
    
    // Default (allowAppendIfMissing = false / undefined)
    const result1 = mergeIndexMdAutoGeneratedBlock(existing, sampleGenerated);
    assert.strictEqual(result1.status, "missing-start-marker");
    assert.strictEqual(result1.mergedMarkdown, existing);
    assert.strictEqual(result1.changed, false);

    // With allowAppendIfMissing = true
    const result2 = mergeIndexMdAutoGeneratedBlock(existing, sampleGenerated, { allowAppendIfMissing: true });
    assert.strictEqual(result2.status, "appended-new-block");
    assert.ok(result2.mergedMarkdown.startsWith(existing));
    assert.ok(result2.mergedMarkdown.includes(AUTO_GENERATED_START_MARKER));
    assert.ok(result2.mergedMarkdown.includes("This is a newly generated AI summary."));
    assert.strictEqual(result2.changed, true);
  });

  test("refuses malformed markers or reversed marker order", () => {
    // Missing end marker
    const result1 = mergeIndexMdAutoGeneratedBlock(`# Intro\n${AUTO_GENERATED_START_MARKER}\nContent\n# Outro`, sampleGenerated);
    assert.strictEqual(result1.status, "missing-end-marker");
    assert.strictEqual(result1.changed, false);

    // Missing start marker
    const result2 = mergeIndexMdAutoGeneratedBlock(`# Intro\nContent\n${AUTO_GENERATED_END_MARKER}\n# Outro`, sampleGenerated);
    assert.strictEqual(result2.status, "missing-start-marker");
    assert.strictEqual(result2.changed, false);

    // Reversed markers
    const reversed = `# Intro\n${AUTO_GENERATED_END_MARKER}\nContent\n${AUTO_GENERATED_START_MARKER}\n# Outro`;
    const result3 = mergeIndexMdAutoGeneratedBlock(reversed, sampleGenerated);
    assert.strictEqual(result3.status, "malformed-marker-order");
    assert.strictEqual(result3.changed, false);
  });

  test("refuses empty generated content", () => {
    const existing = `# Intro\n${AUTO_GENERATED_START_MARKER}\nContent\n${AUTO_GENERATED_END_MARKER}`;
    const result = mergeIndexMdAutoGeneratedBlock(existing, "   \n  ");
    assert.strictEqual(result.status, "empty-generated-content");
    assert.strictEqual(result.changed, false);
    assert.strictEqual(result.mergedMarkdown, existing);
  });
});
