import express from "express";
import path from "path";
import fs from "fs";
import { promises as fsPromises } from "fs";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import { parseOffice } from "officeparser";
import crypto from "crypto";
import { buildScanCacheKeyParts } from "./src/lib/scanCache";
import { mergeIndexMd } from "./src/lib/indexMdMerge";
import { initCacheMetrics, resetCacheMetrics, recordCacheHit, recordCacheMiss, recordCacheWrite, recordCacheBypass, recordCacheError, getCacheMetricsResponse } from "./src/lib/cacheMetrics";
import { getAllPublicSamples, getPublicSampleById } from "./src/lib/visualAnalysis/publicSamples/registry";
import { fetchPublicSampleImage } from "./src/lib/visualAnalysis/publicSamples/serverFetch";
import { 
  buildFileSummaryPrompt, 
  buildFolderSummaryPrompt, 
  buildDebugTextFileSummaryPrompt, 
  buildDebugBinaryFileSummaryPrompt,
  buildSummaryDebugSystemInstruction,
  buildStructuredSummaryTaskPrompt,
  PROMPT_SPEC_VERSION,
  SUMMARY_DEBUG_SYSTEM_INSTRUCTION_VERSION,
  SUMMARY_ANALYSIS_PROMPT_VERSION,
  buildSummaryAnalysisV12Draft2SystemInstruction
} from "./src/lib/promptSpecs";
import { buildAutoGeneratedIndexSection } from "./src/lib/indexMdFormat";
import { SUMMARY_ANALYSIS_SCHEMA_V12, SCHEMA_VERSION_V12 } from "./src/lib/summaryAnalysis/schema";
import { getModelCapability, getStructuredExecutionMode, getVisualModelCapability } from "./src/lib/modelCapabilities";
import { processStructuredSummaryOutput } from "./src/lib/summaryAnalysis/serverUtils";
import { 
  sanitizeResultForResponse, 
  sanitizeResultForCache, 
  sanitizeResultForHistory,
  isDriveContentCacheEnabled
} from "./src/lib/privacyAndCache";
import { buildVisualAnalysisSystemInstruction, buildVisualAnalysisTaskPrompt } from "./src/lib/visualAnalysis/prompts";
import { normalizeVisualAnalysis } from "./src/lib/visualAnalysis/normalize";
import { validateVisualAnalysis } from "./src/lib/visualAnalysis/validate";
import { evaluateVisualAnalysisQuality } from "./src/lib/visualAnalysis/qualityGate";
import { parseModelJsonOutput } from "./src/lib/visualAnalysis/jsonParsing";
import { VISUAL_ANALYSIS_SCHEMA, VISUAL_ANALYSIS_SCHEMA_VERSION } from "./src/lib/visualAnalysis/schema";
import { buildVisualAnalysisRunMetadata, VISUAL_ANALYSIS_GENERATION_CONFIG } from "./src/lib/visualAnalysis/runMetadata";
import { buildGenerationFailureResponse } from "./src/lib/visualAnalysis/generationFailureHelper";
import { generateContentWithRetry } from "./src/lib/gemini";

initCacheMetrics(['scan', 'snippets', 'summaries', 'experimentHistory']);

dotenv.config();

const CACHE_DIR = path.join(process.cwd(), "cache", "snippets");
if (!fs.existsSync(CACHE_DIR)) {
  fs.mkdirSync(CACHE_DIR, { recursive: true });
}

const SUMMARIES_CACHE_DIR = path.join(process.cwd(), "cache", "summaries");
if (!fs.existsSync(SUMMARIES_CACHE_DIR)) {
  fs.mkdirSync(SUMMARIES_CACHE_DIR, { recursive: true });
}

const SCAN_CACHE_DIR = path.join(process.cwd(), "cache", "scan");
if (!fs.existsSync(SCAN_CACHE_DIR)) {
  fs.mkdirSync(SCAN_CACHE_DIR, { recursive: true });
}

function getScanCacheKey(
  parentFolderId: string | undefined, 
  nextPageToken: string | undefined, 
  lastTraversedAt: string | undefined,
  pageSize: number | undefined,
  scanMode: string | undefined,
  cacheScope: string | undefined
): string {
  const parts = buildScanCacheKeyParts(parentFolderId, nextPageToken, lastTraversedAt, pageSize, scanMode, cacheScope);
  return crypto.createHash("md5").update(parts.normalizedString).digest("hex") + ".json";
}

async function getCachedScan(key: string): Promise<any | null> {
  const filePath = path.join(SCAN_CACHE_DIR, key);
  try {
    const content = await fsPromises.readFile(filePath, "utf-8");
    recordCacheHit('scan');
    return JSON.parse(content);
  } catch (err: any) {
    if (err.code === 'ENOENT') {
      recordCacheMiss('scan');
    } else {
      recordCacheError('scan');
    }
    return null;
  }
}

async function setCachedScan(key: string, data: any): Promise<void> {
  const filePath = path.join(SCAN_CACHE_DIR, key);
  try {
    await fsPromises.writeFile(filePath, JSON.stringify(data), "utf-8");
    recordCacheWrite('scan');
  } catch (err) {
    recordCacheError('scan');
    throw err;
  }
}

async function getCachedSnippet(fileId: string): Promise<string | null> {
  if (process.env.ENABLE_DRIVE_CONTENT_CACHE !== 'true') return null;
  const filePath = path.join(CACHE_DIR, `${fileId}.txt`);
  try {
    const content = await fsPromises.readFile(filePath, "utf-8");
    recordCacheHit('snippets');
    return content;
  } catch (err: any) {
    if (err.code === 'ENOENT') {
      recordCacheMiss('snippets');
    } else {
      recordCacheError('snippets');
    }
    return null;
  }
}

async function setCachedSnippet(fileId: string, content: string): Promise<void> {
  if (process.env.ENABLE_DRIVE_CONTENT_CACHE !== 'true') return;
  const filePath = path.join(CACHE_DIR, `${fileId}.txt`);
  try {
    await fsPromises.writeFile(filePath, content, "utf-8");
    recordCacheWrite('snippets');
  } catch (err) {
    recordCacheError('snippets');
    throw err;
  }
}

async function getCachedSummary(key: string): Promise<any | null> {
  const filePath = path.join(SUMMARIES_CACHE_DIR, key);
  try {
    const content = await fsPromises.readFile(filePath, "utf-8");
    recordCacheHit('summaries');
    return JSON.parse(content);
  } catch (err: any) {
    if (err.code === 'ENOENT') {
      recordCacheMiss('summaries');
    } else {
      recordCacheError('summaries');
    }
    return null;
  }
}

async function setCachedSummary(key: string, content: any): Promise<void> {
  const filePath = path.join(SUMMARIES_CACHE_DIR, key);
  try {
    await fsPromises.writeFile(filePath, JSON.stringify(content), "utf-8");
    recordCacheWrite('summaries');
  } catch (err) {
    recordCacheError('summaries');
    throw err;
  }
}

const HISTORY_PATH = path.join(process.cwd(), "src/data/validation_history.json");
const OLD_EXPERIMENT_HISTORY_PATH = path.join(process.cwd(), "src/data/experiment_history.json");

const EXPERIMENT_HISTORY_DIR = path.join(process.cwd(), "cache", "experiment-history");
const EXPERIMENT_HISTORY_PATH = path.join(EXPERIMENT_HISTORY_DIR, "experiment_history.json");

if (!fs.existsSync(EXPERIMENT_HISTORY_DIR)) {
  fs.mkdirSync(EXPERIMENT_HISTORY_DIR, { recursive: true });
}

function extractJsonSchemaFromText(text: string): any {
  if (!text) return null;
  
  let startIdx = -1;
  while ((startIdx = text.indexOf("{", startIdx + 1)) !== -1) {
    let depth = 0;
    let endIdx = -1;
    for (let i = startIdx; i < text.length; i++) {
      if (text[i] === "{") {
        depth++;
      } else if (text[i] === "}") {
        depth--;
        if (depth === 0) {
          endIdx = i;
          break;
        }
      }
    }
    
    if (endIdx !== -1) {
      const potentialJson = text.substring(startIdx, endIdx + 1);
      try {
        const parsed = JSON.parse(potentialJson);
        if (parsed && typeof parsed === "object" && (parsed.type || parsed.properties || parsed.items)) {
          return parsed;
        }
      } catch (e) {
        // keep searching
      }
    }
  }
  return null;
}

function normalizeSchemaForGemini(schema: any): any {
  if (!schema || typeof schema !== "object") return schema;
  
  const normalized: any = { ...schema };
  
  if (typeof normalized.type === "string") {
    const t = normalized.type.toUpperCase();
    if (["OBJECT", "ARRAY", "STRING", "NUMBER", "INTEGER", "BOOLEAN", "NULL"].includes(t)) {
      normalized.type = t;
    }
  }
  
  if (normalized.properties && typeof normalized.properties === "object") {
    const props: any = {};
    for (const [key, val] of Object.entries(normalized.properties)) {
      props[key] = normalizeSchemaForGemini(val);
    }
    normalized.properties = props;
  }
  
  if (normalized.items) {
    normalized.items = normalizeSchemaForGemini(normalized.items);
  }
  
  delete normalized.$schema;
  delete normalized.id;
  delete normalized.$id;
  
  return normalized;
}

function configureStructuredOptions(targetModel: string, configOption: any, jsonModeOverride?: "prompt_only" | "native_schema", customInstruction?: string) {
  configOption.systemInstruction = buildSummaryAnalysisV12Draft2SystemInstruction();
  let execMode = getStructuredExecutionMode(targetModel);
  const cap = getModelCapability(targetModel);

  if (jsonModeOverride === "prompt_only" && execMode === "nativeSchema") {
    execMode = "promptedJson";
  }
  if (jsonModeOverride === "native_schema" && cap.supportsNativeResponseSchema) {
    execMode = "nativeSchema";
  }

  let extractedSchema = null;
  if (cap.supportsNativeResponseSchema && customInstruction) {
    const rawSchema = extractJsonSchemaFromText(customInstruction);
    if (rawSchema) {
      extractedSchema = normalizeSchemaForGemini(rawSchema);
      execMode = "nativeSchema";
    }
  }

  configOption.effectiveStructuredExecutionMode = execMode;
  configOption.supportsNativeResponseSchema = cap.supportsNativeResponseSchema;

  if (execMode === "nativeSchema") {
    configOption.responseMimeType = "application/json";
    configOption.responseSchema = extractedSchema || SUMMARY_ANALYSIS_SCHEMA_V12;
    if (extractedSchema) {
      configOption.extractedCustomSchema = true;
    }
  } else if (execMode === "promptedJson") {
    configOption.systemInstruction += `

CRITICAL INSTRUCTION: You MUST return ONLY a valid JSON object. Do NOT wrap the JSON in Markdown formatting (e.g. \`\`\`json). Just the raw JSON object. Do NOT return an empty object "{}".
You MUST include ALL of the following root sections: "summary", "titleInfo", "documentKindInfo", "fileFormatInfo", "subjectAreas", "languageInfo", "indexing", "extractedFacts", "quality".
You MUST ensure that "summary.oneLine", "titleInfo.inferredTitle", and "titleInfo.displayTitle.value" are non-empty strings.

QUALITY ENHANCEMENT RULES FOR PROMPTED JSON:
1. "documentKindInfo.kinds" MUST contain at least one specific non-unknown kind when any evidence of the document type exists.
2. Google Sheets, Excel files, CSV files, or tabular metadata MUST use "dataset" as the kind.
3. "subjectAreas.domains" MUST include at least one classification domain when the content is classifiable. For YouTube/video metadata, use likely domains such as "technology", "artsAndCulture", or "personal" as appropriate.
4. "indexing.keywords" MUST contain importance values between 0.0 and 1.0 (with at least some non-zero values).
5. If genuinely unclassifiable or unknown, fallback to "unknown", but make every effort to extract meaningful domains/kinds if content details are provided. Avoid hallucination.`;
    delete configOption.responseMimeType;
    delete configOption.responseSchema;
  }
}

function buildRequestPreview(params: any): any {
  return {
    model: params.model,
    requestedOutputMode: params.outputMode,
    effectiveStructuredExecutionMode: params.configOption?.effectiveStructuredExecutionMode || null,
    supportsNativeResponseSchema: params.configOption?.supportsNativeResponseSchema || false,
    responseMimeType: params.configOption?.responseMimeType || null,
    responseSchemaEnabled: !!params.configOption?.responseSchema,
    temperature: params.configOption?.temperature,
    topP: params.configOption?.topP,
    topK: params.configOption?.topK,
    systemInstruction: params.configOption?.systemInstruction || null,
    taskPrompt: params.taskPrompt || null,
    contentSampleLength: params.contentSample?.length || 0,
    contentSamplePreview: params.contentSample ? params.contentSample.substring(0, 500) + (params.contentSample.length > 500 ? "..." : "") : null,
    customInstruction: params.customInstruction || null,
    inputKind: params.inputKind || null,
    mimeType: params.mimeType || null,
    binaryInlineDataUsed: !!params.binaryInlineDataUsed
  };
}

function saveExperimentHistory(entry: any) {
  try {
    let history: any[] = [];
    if (fs.existsSync(EXPERIMENT_HISTORY_PATH)) {
      const content = fs.readFileSync(EXPERIMENT_HISTORY_PATH, "utf-8");
      try {
        history = JSON.parse(content);
      } catch (e) {
        history = [];
      }
    } else if (fs.existsSync(OLD_EXPERIMENT_HISTORY_PATH)) {
      const content = fs.readFileSync(OLD_EXPERIMENT_HISTORY_PATH, "utf-8");
      try {
        history = JSON.parse(content);
      } catch (e) {
        history = [];
      }
    }
    
    if (!Array.isArray(history)) history = [];

    let newEntry = {
      id: `exp-${Date.now()}`,
      timestamp: new Date().toISOString(),
      ...entry
    };
    
    newEntry = sanitizeResultForHistory(newEntry);
    
    // Do not persist rawOutput by default for safety
    delete (newEntry as any).rawOutput;

    history.unshift(newEntry);
    
    if (history.length > 100) {
      history = history.slice(0, 100);
    }

    fs.writeFileSync(EXPERIMENT_HISTORY_PATH, JSON.stringify(history, null, 2));
    recordCacheWrite('experimentHistory');
    return newEntry;
  } catch (e) {
    recordCacheError('experimentHistory');
    console.error("Failed to save experiment history:", e);
    return null;
  }
}

function saveToHistory(entry: {
  status: "success" | "error";
  fileName: string;
  mimeType: string;
  model: string;
  details?: string;
}) {
  try {
    let history = [];
    if (fs.existsSync(HISTORY_PATH)) {
      const content = fs.readFileSync(HISTORY_PATH, "utf-8");
      try {
        history = JSON.parse(content);
      } catch (e) {
        history = [];
      }
    }
    
    // Ensure we have an array
    if (!Array.isArray(history)) history = [];

    const newEntry = {
      id: `auto-${Date.now()}`,
      timestamp: new Date().toISOString(),
      ...entry
    };
    
    history.unshift(newEntry);
    
    // Limit history size to 100 entries to avoid massive files
    if (history.length > 100) {
      history = history.slice(0, 100);
    }

    fs.writeFileSync(HISTORY_PATH, JSON.stringify(history, null, 2));
    return newEntry;
  } catch (e) {
    console.error("Failed to save history:", e);
    return null;
  }
}
export const app = express();
const PORT = 3000;

// Apply JSON parsing middleware
app.use(express.json());



// 1. Health check endpoint
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", time: new Date().toISOString() });
});

// API to fetch history
app.get("/api/validation-history", (req, res) => {
  try {
    if (fs.existsSync(HISTORY_PATH)) {
      const content = fs.readFileSync(HISTORY_PATH, "utf-8");
      return res.json(JSON.parse(content));
    }
    res.json([]);
  } catch (e) {
    res.status(500).json({ error: "Failed to read history" });
  }
});

// API to fetch experiment history
app.get("/api/experiment-history", (req, res) => {
  try {
    if (fs.existsSync(EXPERIMENT_HISTORY_PATH)) {
      const content = fs.readFileSync(EXPERIMENT_HISTORY_PATH, "utf-8");
      return res.json(JSON.parse(content));
    } else if (fs.existsSync(OLD_EXPERIMENT_HISTORY_PATH)) {
      const content = fs.readFileSync(OLD_EXPERIMENT_HISTORY_PATH, "utf-8");
      return res.json(JSON.parse(content));
    }
    res.json([]);
  } catch (e) {
    res.status(500).json({ error: "Failed to read experiment history" });
  }
});

// API to clear experiment history
app.post("/api/experiment-history/clear", (req, res) => {
  try {
    if (fs.existsSync(EXPERIMENT_HISTORY_PATH)) {
      fs.unlinkSync(EXPERIMENT_HISTORY_PATH);
    }
    res.json({ success: true });
  } catch (e) {
    res.status(500).json({ error: "Failed to clear experiment history" });
  }
});

// Helper: safe fetch with error details
async function fetchGoogleDrive(url: string, token: string, options: RequestInit = {}) {
  const mergedOptions = {
    ...options,
    headers: {
      "Authorization": `Bearer ${token}`,
      "Accept": "application/json",
      ...(options.headers || {}),
    }
  };
  const res = await fetch(url, mergedOptions);
  if (!res.ok) {
    const textStatus = await res.text().catch(() => "");
    const err = new Error(`Google API returned status ${res.status}: ${textStatus || res.statusText}`) as any;
    err.status = res.status;
    throw err;
  }
  return res;
}

// Helper: extract Google Drive OAuth token from multiple request locations to handle reverse proxies correctly
function extractToken(req: express.Request): string | null {
  let token: string | undefined;

  // 1. Check standard Authorization header (preferred)
  if (req.headers["authorization"]) {
    const authHeader = req.headers["authorization"] as string;
    if (authHeader.startsWith("Bearer ")) {
      token = authHeader.substring(7);
    } else {
      token = authHeader;
    }
  }

  // 2. Check custom headers (secondary)
  if (!token && req.headers["x-google-drive-token"]) {
    token = req.headers["x-google-drive-token"] as string;
  }
  if (!token && req.headers["X-Google-Drive-Token"]) {
    token = req.headers["X-Google-Drive-Token"] as string;
  }
  
  // 3. Check body params (temporary compatibility path only, do not rely on for new code)
  if (!token && req.body && req.body.token) {
    token = req.body.token as string;
  }

  if (token) {
    const cleaned = token.trim();
    if (cleaned && cleaned !== "null" && cleaned !== "undefined" && cleaned !== "null_token") {
      return cleaned;
    }
  }
  return null;
}

// 2. Fetch User Profile from Google API (validate token)
app.get("/api/drive/user", async (req, res) => {
  const token = extractToken(req);
  if (!token) {
    res.status(401).json({ error: "Missing x-google-drive-token header" });
    return;
  }
  try {
    const response = await fetchGoogleDrive("https://www.googleapis.com/oauth2/v2/userinfo", token);
    const data = await response.json();
    res.json(data);
  } catch (err: any) {
    res.status(401).json({ error: err.message || "Failed to validate token with Google User Info" });
  }
});

// 3. Drive lists directories endpoint (Supports incremental scans, full lists, and step-by-step debug scans)
// q: 'root' in parents, modifiedTime > datetime, mimeType='application/vnd.google-apps.folder', trashed=false
app.post("/api/drive/scan", async (req, res) => {
  const token = extractToken(req);
  if (!token) {
    res.status(401).json({ error: "Missing x-google-drive-token header" });
    return;
  }

  const { lastTraversedAt, nextPageToken, pageSize, parentFolderId, scanMode, bypassCache, cacheScope } = req.body;
  const targetPageSize = pageSize || 100;
  const cacheKey = getScanCacheKey(parentFolderId, nextPageToken, lastTraversedAt, targetPageSize, scanMode, cacheScope);

  try {
    // 1. Try reading from disk cache
    if (!bypassCache) {
      const cachedData = await getCachedScan(cacheKey);
      if (cachedData) {
        console.log(`[Cache Hit] mode=${scanMode || "none"} scope=${cacheScope || "none"} key=${cacheKey.substring(0, 8)}... Serving scan result from disk cache.`);
        res.json({ ...cachedData, cached: true });
        return;
      }
    } else {
      recordCacheBypass('scan');
      console.log(`[Cache Bypass] mode=${scanMode || "none"} skip disk cache read.`);
    }

    // 2. Fetch from Google API on cache miss
    let q = "(mimeType = 'application/vnd.google-apps.folder' or (mimeType = 'application/vnd.google-apps.shortcut' and shortcutDetails.targetMimeType = 'application/vnd.google-apps.folder')) and trashed = false";
    
    if (parentFolderId) {
      q = `'${parentFolderId}' in parents and ${q}`;
    } else if (lastTraversedAt) {
      q += ` and modifiedTime > '${lastTraversedAt}'`;
    }

    const fields = "nextPageToken,files(id,name,mimeType,parents,modifiedTime,shortcutDetails)";
    let url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=${encodeURIComponent(fields)}&pageSize=${targetPageSize}`;
    if (nextPageToken) {
      url += `&pageToken=${encodeURIComponent(nextPageToken)}`;
    }

    console.log(`[Cache Miss] Fetching scan result from Google Drive API`);
    const response = await fetchGoogleDrive(url, token);
    const data = await response.json();

    // 3. Save to disk cache if it's a successful response (has no error key)
    if (!bypassCache && data && !data.error) {
      await setCachedScan(cacheKey, data);
    }

    res.json({ ...data, cached: false });
  } catch (err: any) {
    // If the pageToken is stale, expired, or invalid, Google Drive API returns status 400 with 'pageToken' in the error details.
    // We can auto-recover by retrying the request without the pageToken to fetch page 1 fresh.
    if (err.status === 400 && nextPageToken && err.message && err.message.includes("pageToken")) {
      console.warn(`[PageToken Recovery] Stale/invalid pageToken detected for folder ${parentFolderId || "root"}. Auto-recovering by requesting page 1 fresh...`);
      try {
        let q = "(mimeType = 'application/vnd.google-apps.folder' or (mimeType = 'application/vnd.google-apps.shortcut' and shortcutDetails.targetMimeType = 'application/vnd.google-apps.folder')) and trashed = false";
        if (parentFolderId) {
          q = `'${parentFolderId}' in parents and ${q}`;
        } else if (lastTraversedAt) {
          q += ` and modifiedTime > '${lastTraversedAt}'`;
        }

        const fields = "nextPageToken,files(id,name,mimeType,parents,modifiedTime,shortcutDetails)";
        const urlWithoutToken = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=${encodeURIComponent(fields)}&pageSize=${targetPageSize}`;
        
        console.log(`[PageToken Recovery] Re-fetching page 1 from Google Drive API without pageToken`);
        const recoveryResponse = await fetchGoogleDrive(urlWithoutToken, token);
        const recoveryData = await recoveryResponse.json();

        // Save to disk cache under the original key so subsequent scans can hit it
        if (!bypassCache && recoveryData && !recoveryData.error) {
          await setCachedScan(cacheKey, recoveryData);
        }

        res.json({ ...recoveryData, cached: false, pageTokenRecovered: true });
        return;
      } catch (recoveryErr: any) {
        console.error(`[PageToken Recovery Failed]`, recoveryErr);
      }
    }

    const statusCode = err.status || 500;
    res.status(statusCode).json({ error: err.message || "Drive scan failed" });
  }
});

// Endpoint to manually or programmatically clear the folder scan disk cache
app.post("/api/drive/clear-scan-cache", async (req, res) => {
  try {
    const files = await fsPromises.readdir(SCAN_CACHE_DIR);
    for (const file of files) {
      await fsPromises.unlink(path.join(SCAN_CACHE_DIR, file));
    }
    console.log("[Cache Reset] Cleared all folder scan files from disk cache.");
    res.json({ success: true, message: "Folder scan cache cleared successfully." });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to clear scan cache" });
  }
});

// Endpoint to manually clear specific or all caches individually
app.post("/api/drive/clear-cache", async (req, res) => {
  const { type } = req.body; // "scan" | "snippets" | "summaries" | "all"
  try {
    const clearDir = async (dirPath: string) => {
      if (!fs.existsSync(dirPath)) return;
      const files = await fsPromises.readdir(dirPath);
      for (const file of files) {
        await fsPromises.unlink(path.join(dirPath, file));
      }
    };

    const clearedTypes: string[] = [];

    if (type === "scan" || type === "all" || !type) {
      await clearDir(SCAN_CACHE_DIR);
      clearedTypes.push("フォルダ走査結果(scan)");
    }
    if (type === "snippets" || type === "all") {
      await clearDir(CACHE_DIR);
      clearedTypes.push("ファイルテキストスニペット(snippets)");
    }
    if (type === "summaries" || type === "all") {
      await clearDir(SUMMARIES_CACHE_DIR);
      clearedTypes.push("AI要約(summaries)");
    }

    console.log(`[Cache Reset] Cleared caches: ${clearedTypes.join(", ")}`);
    res.json({ success: true, message: `${clearedTypes.join(", ")} キャッシュが正常にクリアされました。` });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to clear cache" });
  }
});

// 4. Detailed file cataloguing and single folder index generator
app.post("/api/drive/generate-index-step", async (req, res) => {
  const token = extractToken(req);
  if (!token) {
    res.status(401).json({ error: "Missing x-google-drive-token" });
    return;
  }

  const { folderId, folderName, config, subdirsWithSummaries } = req.body;
  if (!folderId || !folderName) {
    res.status(400).json({ error: "folderId and folderName are required params." });
    return;
  }

  const rateDelay = config?.rate_limit_delay_ms || 500;
  const geminiModel = config?.gemini_model || "gemini-2.5-flash";

  try {
    // Step 1: List all files and folders immediately under this folder
    const listQ = `'${folderId}' in parents and trashed = false`;
    const listFields = "files(id,name,mimeType,size,webViewLink,shortcutDetails)";
    const listUrl = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(listQ)}&fields=${encodeURIComponent(listFields)}&pageSize=1000`;
    
    const listRes = await fetchGoogleDrive(listUrl, token);
    const listData = await listRes.json();
    const items = listData.files || [];

    if (items.length === 0) {
      res.json({
        success: true,
        message: "Folder is empty, skipped AI summarization as per rules.",
        skipped: true,
        files: [],
        subdirectories: []
      });
      return;
    }

    // Separate folders and files while resolving shortcuts
    const files: any[] = [];
    const subdirs: any[] = [];

    for (const item of items) {
      let resolvedMimeType = item.mimeType;
      let resolvedId = item.id;
      
      if (item.mimeType === "application/vnd.google-apps.shortcut" && item.shortcutDetails) {
        resolvedMimeType = item.shortcutDetails.targetMimeType;
        resolvedId = item.shortcutDetails.targetId;
      }

      const itemInfo = {
        id: item.id,
        resolvedId,
        name: item.name,
        mimeType: resolvedMimeType,
        size: item.size || 0,
        webViewLink: item.webViewLink || `https://drive.google.com/open?id=${item.id}`
      };

      if (resolvedMimeType === "application/vnd.google-apps.folder") {
        subdirs.push(itemInfo);
      } else {
        files.push(itemInfo);
      }
    }

    // Step 2: Individual file summaries processing
    const fileSummariesList: string[] = [];
    
    // We parse up to a maximum to prevent exceeding limits
    const filesSubset = files.slice(0, 15);
    for (const file of filesSubset) {
      let contentSample = "";
      
      // Attempt to load text content of readable files for richer AI context
      const isReadable = [
        "text/plain", "text/markdown", "application/json", "text/csv", "text/html", "application/xml"
      ].includes(file.mimeType);

      const isGoogleDoc = [
        "application/vnd.google-apps.document",
        "application/vnd.google-apps.spreadsheet",
        "application/vnd.google-apps.presentation"
      ].includes(file.mimeType);

      if (isReadable || isGoogleDoc) {
        try {
          let contentUrl = `https://www.googleapis.com/drive/v3/files/${file.resolvedId}?alt=media`;
          if (file.mimeType === "application/vnd.google-apps.document") {
            contentUrl = `https://www.googleapis.com/drive/v3/files/${file.resolvedId}/export?mimeType=text/plain`;
          } else if (file.mimeType === "application/vnd.google-apps.spreadsheet") {
            contentUrl = `https://www.googleapis.com/drive/v3/files/${file.resolvedId}/export?mimeType=text/csv`;
          } else if (file.mimeType === "application/vnd.google-apps.presentation") {
            contentUrl = `https://www.googleapis.com/drive/v3/files/${file.resolvedId}/export?mimeType=text/plain`;
          }

          const contentRes = await fetchGoogleDrive(contentUrl, token);
          const fullText = await contentRes.text();
          contentSample = fullText.substring(0, 1500); // Take first 1500 chars to avoid token inflation
        } catch (downloadErr) {
          // Fallback to name-only summary
          contentSample = "";
        }
      }

      // Query Gemini for single file summary
      try {
        const filePrompt = buildFileSummaryPrompt({
          name: file.name,
          mimeType: file.mimeType,
          size: file.size,
          contentSample: contentSample
        });
        
        const aiRes = await generateContentWithRetry(geminiModel, filePrompt);

        const singleSummary = aiRes.text?.trim() || "ファイルの記述がありません。";
        fileSummariesList.push(`- **${file.name}**: ${singleSummary}`);
      } catch (aiErr: any) {
        fileSummariesList.push(`- **${file.name}**: (名前情報から構成)`);
      }

      // Inject custom rate pacing
      await new Promise(resolve => setTimeout(resolve, rateDelay));
    }

    // Capture remaining files (beyond the subset limit)
    if (files.length > 15) {
      files.slice(15).forEach(f => {
        fileSummariesList.push(`- **${f.name}**: その他追加資料`);
      });
    }

    // Step 3: Combine into a single Directory Summary
    let folderSummary = "";
    try {
      const combinedPrompt = buildFolderSummaryPrompt({
        folderName,
        subdirs: subdirs.map(d => {
          const match = subdirsWithSummaries?.find((s: any) => s.id === d.id);
          return { name: d.name, summary: match?.summary };
        }),
        fileSummariesList
      });

      const combinedAiRes = await generateContentWithRetry(geminiModel, combinedPrompt);

      folderSummary = combinedAiRes.text?.trim() || `フォルダ「${folderName}」のコンテンツの概要です。`;
    } catch (summaryErr: any) {
      folderSummary = `フォルダ「${folderName}」の自動AI要約です。ファイルを安全に検出し、インデックスしました。`;
    }

    // Step 4: Seek index.md in the folder to see if target already exists (Seeding Hybrid-merge rules)
    const indexCheckQ = `'${folderId}' in parents and name = 'index.md' and trashed = false`;
    const indexCheckUrl = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(indexCheckQ)}&fields=files(id,name)`;
    const indexCheckRes = await fetchGoogleDrive(indexCheckUrl, token);
    const indexCheckData = await indexCheckRes.json();
    const existingIndexFile = indexCheckData.files?.[0];

    let currentFileContent = "";
    let existingIndexId = existingIndexFile?.id || null;

    if (existingIndexId) {
      try {
        const fetchContentUrl = `https://www.googleapis.com/drive/v3/files/${existingIndexId}?alt=media`;
        const contentRes = await fetchGoogleDrive(fetchContentUrl, token);
        currentFileContent = await contentRes.text();
      } catch (fetchContentErr) {
        currentFileContent = "";
      }
    }

    // Prepare OKF sections
    const nowIso = new Date().toISOString();
    const autoGenStartMarker = "<!-- AUTO_GENERATED_START -->";
    const autoGenEndMarker = "<!-- AUTO_GENERATED_END -->";

    // Subdirectories list with Google Drive links
    const mdSubdirsText = subdirs.map(sub => {
      // Create relative path preview and point direct Web link or custom layout
      return `- [${sub.name}/](${sub.webViewLink})`;
    }).join("\n");

    // Files list with individual descriptions
    const mdFilesText = files.map(file => {
      return `- [${file.name}](${file.webViewLink})`;
    }).join("\n");

    const autoGenSectionContent = buildAutoGeneratedIndexSection({
      folderSummary,
      mdFilesText,
      mdSubdirsText,
      nowIso
    });

    // Process Hybrid Merge
    const mergedContent = mergeIndexMd(currentFileContent, folderName, autoGenSectionContent);

    // Step 5: Save/Update in Google Drive
    if (existingIndexId) {
      // Perform PATCH update
      const updateUrl = `https://www.googleapis.com/upload/drive/v3/files/${existingIndexId}?uploadType=media`;
      await fetchGoogleDrive(updateUrl, token, {
        method: "PATCH",
        headers: { "Content-Type": "text/markdown" },
        body: mergedContent
      });
    } else {
      // Create new file
      // 1. Create Metadata
      const createMetaUrl = "https://www.googleapis.com/drive/v3/files";
      const createMetaRes = await fetchGoogleDrive(createMetaUrl, token, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: "index.md",
          mimeType: "text/markdown",
          parents: [folderId]
        })
      });
      const createdFileInfo = await createMetaRes.json();
      existingIndexId = createdFileInfo.id;

      // 2. Upload media
      const updateUrl = `https://www.googleapis.com/upload/drive/v3/files/${existingIndexId}?uploadType=media`;
      await fetchGoogleDrive(updateUrl, token, {
        method: "PATCH",
        headers: { "Content-Type": "text/markdown" },
        body: mergedContent
      });
    }

    res.json({
      success: true,
      indexFileId: existingIndexId,
      aiSummary: folderSummary,
      filesGenerated: files.length,
      subdirsGenerated: subdirs.length
    });

  } catch (err: any) {
    console.error("Index generation error:", err);
    const statusCode = err.status || 500;
    res.status(statusCode).json({ error: err.message || "Failed to generate index files." });
  }
});

app.get("/api/drive/debug/sample-files", async (req, res) => {
  const token = extractToken(req);
  if (!token) {
    res.status(401).json({ error: "Missing x-google-drive-token header" });
    return;
  }

  const mimeTypes = [
    { type: "application/pdf", name: "PDF" },
    { type: "application/vnd.google-apps.document", name: "Google ドキュメント" },
    { type: "application/vnd.google-apps.spreadsheet", name: "Google スプレッドシート" },
    { type: "application/vnd.google-apps.presentation", name: "Google スライド" },
    { type: "text/plain", name: "プレーンテキスト" },
    { type: "text/markdown", name: "Markdown" },
    { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", name: "MS Word" },
    { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", name: "MS Excel" },
    { type: "application/vnd.openxmlformats-officedocument.presentationml.presentation", name: "MS PowerPoint" },
    { type: "application/json", name: "JSON" },
    { type: "text/csv", name: "CSV" },
    { type: "image/jpeg", name: "画像 (JPEG)" },
    { type: "image/png", name: "画像 (PNG)" }
  ];

  try {
    const results = [];
    for (const mime of mimeTypes) {
      const q = `mimeType = '${mime.type}' and trashed = false`;
      const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id,name,mimeType)&pageSize=1`;
      const driveRes = await fetchGoogleDrive(url, token);
      const data = await driveRes.json();
      
      if (data.files && data.files.length > 0) {
        results.push({
          category: mime.name,
          file: data.files[0]
        });
      }
    }
    res.json({ samples: results });
  } catch (err: any) {
    res.status(err.status || 500).json({ error: err.message });
  }
});

/**
 * Part B: Read-only Drive lookup for index.md in the selected folder.
 * Queries only the selected folder's direct children for the name "index.md".
 */
app.get("/api/drive/index-preflight/lookup", async (req, res) => {
  const token = extractToken(req);
  if (!token) {
    res.status(401).json({ error: "Missing x-google-drive-token header" });
    return;
  }

  const { folderId } = req.query;
  if (!folderId) {
    res.status(400).json({ error: "folderId query parameter is required" });
    return;
  }

  try {
    const q = `'${folderId}' in parents and name = 'index.md' and trashed = false`;
    const fields = "files(id,name,mimeType,modifiedTime,parents)";
    const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=${encodeURIComponent(fields)}`;
    
    const response = await fetchGoogleDrive(url, token);
    const data = await response.json();
    
    // Part B: 18. Safe metadata may be shown: fileId, fileName, mimeType, modifiedTime, parentId
    const candidates = (data.files || []).map((f: any) => ({
      fileId: f.id,
      fileName: f.name,
      mimeType: f.mimeType,
      modifiedTime: f.modifiedTime,
      parentId: f.parents?.[0]
    }));

    res.json({ candidates });
  } catch (err: any) {
    res.status(err.status || 500).json({ error: err.message || "Failed to lookup index.md" });
  }
});

/**
 * Part C: Read-only fetch of existing index.md content.
 */
app.get("/api/drive/index-preflight/content", async (req, res) => {
  const token = extractToken(req);
  if (!token) {
    res.status(401).json({ error: "Missing x-google-drive-token header" });
    return;
  }

  const { fileId } = req.query;
  if (!fileId) {
    res.status(400).json({ error: "fileId query parameter is required" });
    return;
  }

  try {
    const url = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;
    const response = await fetchGoogleDrive(url, token);
    const content = await response.text();
    
    res.json({ content });
  } catch (err: any) {
    res.status(err.status || 500).json({ error: err.message || "Failed to fetch index.md content" });
  }
});


const SUMMARY_ANALYSIS_REPAIR_VERSION = "1.0.0";

app.post("/api/drive/debug/generate-file-summary", async (req, res) => {
  const token = extractToken(req);
  if (!token) {
    res.status(401).json({ error: "Missing x-google-drive-token header" });
    return;
  }

  const { fileId, modelName, temperature, topP, topK, customInstruction, outputMode, includeRequestPreview, jsonMode } = req.body;
  if (!fileId) {
    return res.status(400).json({ error: "fileId is required" });
  }

  const targetModel = modelName || "gemini-3.5-flash"; // default fallback if empty
  const temp = temperature || 0;
  const tP = topP || 0;
  const tK = topK || 0;
  const mode = outputMode === "structured" ? "structured" : "text";
  
  try {
    // 1. Get file metadata (we need this first to include modifiedTime in cache key)
    const metaUrl = `https://www.googleapis.com/drive/v3/files/${fileId}?fields=id,name,mimeType,size,modifiedTime`;
    const metaRes = await fetchGoogleDrive(metaUrl, token);
    const fileMeta = await metaRes.json();

    // Sanitize model name so it is safe to use in a filename
    const safeModel = targetModel.replace(/[^a-zA-Z0-9_-]/g, "_");
    const modTime = fileMeta.modifiedTime ? new Date(fileMeta.modifiedTime).getTime() : 0;
    
    // Hash custom instruction for cache key
    const instructionHash = customInstruction ? crypto.createHash('md5').update(customInstruction).digest("hex").substring(0, 8) : "default";

    let cacheKey = "";
    if (mode === "structured") {
      cacheKey = `${fileId}__${safeModel}__${temp}__${tP}__${tK}__mode_${mode}__v${SUMMARY_ANALYSIS_PROMPT_VERSION.replace(/\./g, '_')}__sys_${SUMMARY_DEBUG_SYSTEM_INSTRUCTION_VERSION.replace(/\./g, '_')}__sch_${SCHEMA_VERSION_V12.replace(/\./g, '_')}__rep_${SUMMARY_ANALYSIS_REPAIR_VERSION.replace(/\./g, '_')}__${instructionHash}__${modTime}.json`;
    } else {
      cacheKey = `${fileId}__${safeModel}__${temp}__${tP}__${tK}__mode_${mode}__v${PROMPT_SPEC_VERSION.replace(/\./g, '_')}__${instructionHash}__${modTime}.json`;
    }

    // 0. Check cache
    const cachedSummary = await getCachedSummary(cacheKey);
    if (cachedSummary) return res.json(cachedSummary);
    
    // 2. Export / Download content
    const mimeType = fileMeta.mimeType || "";
    let contentUrl = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;
    let isReadable = false;

    if (mimeType === "application/vnd.google-apps.document") {
      contentUrl = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=text/plain`;
      isReadable = true;
    } else if (mimeType === "application/vnd.google-apps.spreadsheet") {
      contentUrl = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=text/csv`;
      isReadable = true;
    } else if (mimeType === "application/vnd.google-apps.presentation") {
      contentUrl = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=text/plain`;
      isReadable = true;
    } else if (mimeType === "application/pdf") {
      // For PDF, we can try alt=media download but standard full-text decode might need a library. 
      // We will attempt raw download and Gemini multimodal if that model supports it. But Gemma might need raw text.
      // We'll pass text to Gemini/Gemma. Raw PDF binary string isn't readable text directly.
      isReadable = true;
    } else if (["text/plain", "text/markdown", "application/json", "text/csv"].includes(mimeType)) {
      isReadable = true;
    } else if (mimeType.startsWith("application/vnd.openxmlformats-officedocument")) {
      isReadable = true;
    } else if (mimeType.startsWith("image/")) {
      isReadable = true;
    }

    let fullText = "";
    
    // Check if we can use cached text snippet
    const cachedSnippet = await getCachedSnippet(fileId);
    if (cachedSnippet) {
      fullText = cachedSnippet;
    } else if (isReadable) {
      if (mimeType === "application/pdf" || mimeType.startsWith("image/")) {
         // ... (Binary data, don't cache as text snippet)
         try {
           const fileRes = await fetchGoogleDrive(contentUrl, token);
           const arrBuffer = await fileRes.arrayBuffer();
           const base64Data = Buffer.from(arrBuffer).toString("base64");
           
           // Query Gemini with binary part directly
           let filePrompt = "";
           let configOption: any = { temperature: temp, topP: tP, topK: tK };
           
           if (mode === "structured") {
             filePrompt = buildStructuredSummaryTaskPrompt({
               name: fileMeta.name,
               mimeType: fileMeta.mimeType
             }, customInstruction);
             configureStructuredOptions(targetModel, configOption);
           } else {
             filePrompt = buildDebugBinaryFileSummaryPrompt({
               name: fileMeta.name,
               mimeType: fileMeta.mimeType
             }, customInstruction);
           }

           const aiRes = await generateContentWithRetry(targetModel, [
             { inlineData: { data: base64Data, mimeType: mimeType } },
             { text: filePrompt }
           ], 4, configOption);
           
           const summaryText = aiRes.text?.trim() || (mode === "structured" ? "{}" : "No summary generated");
           
           let result: any = {
             success: true,
             outputMode: mode,
             metadata: fileMeta,
             contentSampleSnippet: `(${mimeType.split('/')[0].toUpperCase()} binary data was passed directly to the model)`
           };

           if (mode === "structured") {
             const processed = await processStructuredSummaryOutput(summaryText, targetModel, configOption);
             result = { ...result, ...processed };
             if (processed.error) result.success = false;
           } else {
             result.summary = summaryText;
           }

           if (includeRequestPreview) {
             result.requestPreview = buildRequestPreview({
               model: targetModel,
               outputMode: mode,
               configOption,
               taskPrompt: filePrompt,
               contentSample: null,
               customInstruction,
               inputKind: "driveFile",
               mimeType: mimeType,
               binaryInlineDataUsed: true
             });
           }

           const responseResult = sanitizeResultForResponse(result);
           const cacheResult = sanitizeResultForCache(result);
           if (mode !== "structured" || result.success) { await setCachedSummary(cacheKey, cacheResult); }
           // Save to Experiment History
            saveExperimentHistory({
              inputKind: "driveFile",
              inputLabel: fileMeta.name,
              fileMetadata: {
                name: fileMeta.name,
                mimeType: fileMeta.mimeType
              },
              model: targetModel,
              outputMode: mode,
              schemaVersion: SCHEMA_VERSION_V12,
              parseSuccess: result.success && !result.structuredParseFailed,
              validationSuccess: result.success && !result.structuredParseFailed && !result.error,
              structuredResult: result.structured,
              validationErrors: result.validationErrors,
              warnings: result.warnings,
              repairApplied: result.repairApplied,
              repairFallbackUsed: result.repairFallbackUsed,
              error: result.error
            });

            return res.json(responseResult);
         } catch(e: any) {
           return res.status(500).json({ error: `${mimeType.startsWith('image') ? 'Image' : 'PDF'} generation failed: ${e.message}` });
         }
      } else if (mimeType.startsWith("application/vnd.openxmlformats-officedocument")) {
         try {
           const officeRes = await fetchGoogleDrive(contentUrl, token);
           const arrBuffer = await officeRes.arrayBuffer();
           // officeparser.parseOffice returns the text directly as a string if no callback is provided
           const parsedText = await parseOffice(Buffer.from(arrBuffer));
           if (typeof parsedText === 'string') {
             fullText = parsedText;
           } else if (parsedText && typeof parsedText === 'object') {
             fullText = (parsedText as any).text || JSON.stringify(parsedText);
           } else {
             fullText = String(parsedText);
           }
           await setCachedSnippet(fileId, fullText);
         } catch(e: any) {
           console.error("Office parsing error:", e);
           fullText = `Office parsing failed: ${e.message}`;
         }
      } else {
        const contentRes = await fetchGoogleDrive(contentUrl, token);
        fullText = await contentRes.text();
        await setCachedSnippet(fileId, fullText);
      }
    } else {
      fullText = "This file type is not natively extractable as text in this debug tool.";
    }

    // 3. Query Model for standard text
    const contentSample = fullText.substring(0, 50000); // 50k chars max to avoid 500 error on gemma models
    
    let filePrompt = "";
    let configOption: any = { temperature: temp, topP: tP, topK: tK };
    
    if (mode === "structured") {
      filePrompt = buildStructuredSummaryTaskPrompt({
        name: fileMeta.name,
        mimeType: fileMeta.mimeType,
        contentSample: contentSample
      }, customInstruction);
      configureStructuredOptions(targetModel, configOption, jsonMode, customInstruction);
    } else {
      filePrompt = buildDebugTextFileSummaryPrompt({
        name: fileMeta.name,
        mimeType: fileMeta.mimeType,
        contentSample: contentSample
      }, customInstruction);
    }

    const aiRes = await generateContentWithRetry(targetModel, filePrompt, 4, configOption);

    const summaryText = aiRes.text?.trim() || (mode === "structured" ? "{}" : "No summary generated");

    let result: any = {
      success: true,
      outputMode: mode,
      metadata: fileMeta,
      contentSampleSnippet: contentSample.substring(0, 200) + (contentSample.length > 200 ? "..." : "")
    };

    if (mode === "structured") {
      const processed = await processStructuredSummaryOutput(summaryText, targetModel, configOption);
      result = { ...result, ...processed };
      if (processed.error) result.success = false;
    } else {
      result.summary = summaryText;
    }

    // Save to Experiment History
    saveExperimentHistory({
      inputKind: "driveFile",
      inputLabel: fileMeta.name,
      fileMetadata: {
        name: fileMeta.name,
        mimeType: fileMeta.mimeType
      },
      model: targetModel,
      outputMode: mode,
      schemaVersion: SCHEMA_VERSION_V12,
      parseSuccess: result.success && !result.structuredParseFailed,
      validationSuccess: result.success && !result.structuredParseFailed && !result.error,
      structuredResult: result.structured,
      validationErrors: result.validationErrors,
      warnings: result.warnings,
      repairApplied: result.repairApplied,
      repairFallbackUsed: result.repairFallbackUsed,
      error: result.error
    });

    if (includeRequestPreview) {
      result.requestPreview = buildRequestPreview({
        model: targetModel,
        outputMode: mode,
        configOption,
        taskPrompt: filePrompt,
        contentSample: contentSample,
        customInstruction,
        inputKind: "driveFile",
        mimeType: mimeType,
        binaryInlineDataUsed: false
      });
    }

    const responseResult = sanitizeResultForResponse(result);
    const cacheResult = sanitizeResultForCache(result);
    if (mode !== "structured" || result.success) { await setCachedSummary(cacheKey, cacheResult); }
    
    res.json(responseResult);
  } catch (err: any) {
    console.error("Debug file summary error:", err);
    let errorMessage = "要約の生成に失敗しました。";
    
    // Attempt meta fetch if it failed late
    let failName = "Unknown File";
    let failMime = "unknown";
    try {
      const metaUrl = `https://www.googleapis.com/drive/v3/files/${fileId}?fields=name,mimeType`;
      const metaRes = await fetchGoogleDrive(metaUrl, token);
      const fileMeta = await metaRes.json();
      failName = fileMeta.name;
      failMime = fileMeta.mimeType;
    } catch(e) {}
    
    // Extract message from ApiError or standard Error
    const rawMessage = err.message || "";
    const errorBody = err.response?.error || err.error || {};
    
    if (rawMessage.includes("503") || rawMessage.includes("high demand") || errorBody.code === 503) {
      errorMessage = "選択したモデルが混み合っています (503)。しばらく待ってから再試行するか、別のモデル（gemini-3.1-flash-lite など）をお試しください。";
    } else if (rawMessage.includes("API key not valid")) {
      errorMessage = "Gemini APIキーが無効です。設定をご確認ください。";
    } else if (rawMessage.includes("RESOURCE_EXHAUSTED") || rawMessage.includes("quota") || errorBody.status === "RESOURCE_EXHAUSTED") {
      errorMessage = "Gemini APIの利用制限（リクエスト過多・クォータ不足）に達しました。時間を置いてください。";
    } else if (rawMessage.includes("SAFETY")) {
      errorMessage = "安全性のフィルタリングにより要約を生成できませんでした。";
    } else {
      errorMessage = err.message || "Failed to generate file summary.";
    }

    const rawStatus = err.statusCode || err.status || err.response?.status;
    const statusCode = rawStatus ? Number(rawStatus) : 500;
    
    let errorResponse: any = { error: errorMessage };
    if (err.name === "ProviderError") {
      errorResponse.providerError = {
        statusCode: err.statusCode,
        providerStatus: err.providerStatus,
        rawMessageSummary: err.rawMessageSummary
      };
    }
    
    res.status(statusCode).json(errorResponse);
  }
});


app.post("/api/drive/debug/generate-manual-summary", async (req, res) => {
  try {
    const { text, customInstruction, modelName, outputMode, inputLabel, includeRequestPreview, jsonMode } = req.body;
    if (!text || typeof text !== "string") {
      return res.status(400).json({ error: "Missing or invalid 'text' field" });
    }

    const targetModel = modelName || "gemini-3.5-flash";
    const mode = outputMode === "structured" ? "structured" : "text";
    const temp = 0.2;
    const tP = 0.95;
    const tK = 64;

    const contentSample = text.substring(0, 50000);
    
    let prompt = "";
    let configOption: any = { temperature: temp, topP: tP, topK: tK };
    
    if (mode === "structured") {
      prompt = buildStructuredSummaryTaskPrompt({
        name: "Manual Text Input",
        mimeType: "text/plain",
        contentSample: contentSample
      }, customInstruction);
      configureStructuredOptions(targetModel, configOption, jsonMode, customInstruction);
    } else {
      prompt = buildDebugTextFileSummaryPrompt({
        name: "Manual Text Input",
        mimeType: "text/plain",
        contentSample: contentSample
      }, customInstruction);
    }

    const aiRes = await generateContentWithRetry(targetModel, prompt, 4, configOption);
    const summaryText = aiRes.text?.trim() || (mode === "structured" ? "{}" : "No summary generated");

    let result: any = {
      success: true,
      outputMode: mode,
      metadata: { name: "Manual Text Input", mimeType: "text/plain" },
      contentSampleSnippet: contentSample.substring(0, 200) + (contentSample.length > 200 ? "..." : "")
    };

    if (mode === "structured") {
      const processed = await processStructuredSummaryOutput(summaryText, targetModel, configOption);
      result = { ...result, ...processed };
      if (processed.error) result.success = false;
    } else {
      result.summary = summaryText;
    }

    // Hash the text just to store some uniqueness indicator
    let textHash = 0;
    for (let i = 0; i < text.length; i++) {
      textHash = ((textHash << 5) - textHash) + text.charCodeAt(i);
      textHash |= 0;
    }

    saveExperimentHistory({
      inputKind: "manualText",
      inputLabel: inputLabel || `Manual Text (${text.length} chars)`,
      model: targetModel,
      outputMode: mode,
      schemaVersion: SCHEMA_VERSION_V12,
      parseSuccess: result.success && !result.structuredParseFailed,
      validationSuccess: result.success && !result.structuredParseFailed && !result.error,
      structuredResult: result.structured,
      validationErrors: result.validationErrors,
      warnings: result.warnings,
      repairApplied: result.repairApplied,
      repairFallbackUsed: result.repairFallbackUsed,
      error: result.error,
      manualTextHash: textHash.toString(16)
    });

    if (includeRequestPreview) {
      result.requestPreview = buildRequestPreview({
        model: targetModel,
        outputMode: mode,
        configOption,
        taskPrompt: prompt,
        contentSample: contentSample,
        customInstruction,
        inputKind: "manualText",
        mimeType: "text/plain",
        binaryInlineDataUsed: false
      });
    }

    res.json(sanitizeResultForResponse(result));
  } catch (err: any) {
    console.error("Manual text summary error:", err);
    const rawStatus = err.statusCode || err.status || err.response?.status;
    const statusCode = rawStatus ? Number(rawStatus) : 500;
    
    let errorResponse: any = { error: err.message || "Failed to process manual text" };
    if (err.name === "ProviderError") {
      errorResponse.providerError = {
        statusCode: err.statusCode,
        providerStatus: err.providerStatus,
        rawMessageSummary: err.rawMessageSummary
      };
    }
    
    res.status(statusCode).json(errorResponse);
  }
});


app.get("/api/visual/public-samples", (req, res) => {
  const samples = getAllPublicSamples().map(s => ({
    id: s.id,
    title: s.title,
    category: s.category,
    expectedImageKind: s.expectedImageKind,
    expectedElementCategories: s.expectedElementCategories,
    expectedVisibleElementLabels: s.expectedVisibleElementLabels,
    thumbnailRoute: `/api/visual/public-samples/${s.id}/image?variant=thumbnail`,
    licenseKind: s.source.licenseKind,
    licenseName: s.source.licenseName,
    attributionText: s.source.attributionText,
    sourcePageUrl: s.source.pageUrl
  }));
  res.json(samples);
});

app.get("/api/visual/public-samples/:sampleId/image", async (req, res) => {
  try {
    const { sampleId } = req.params;
    const variant = (req.query.variant as any) || "full";
    if (!["preview", "thumbnail", "full", "analysis"].includes(variant)) {
      return res.status(400).json({ error: "Invalid variant" });
    }

    const result = await fetchPublicSampleImage(sampleId, variant as "preview" | "thumbnail" | "full" | "analysis");

    // Set safe headers
    res.setHeader("Content-Type", result.mimeType);
    res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate");
    res.setHeader("Pragma", "no-cache");
    res.setHeader("Expires", "0");
    res.setHeader("Surrogate-Control", "no-store");

    res.send(result.buffer);
  } catch (err: any) {
    if (err.message.includes("not found")) {
      return res.status(404).json({ error: "Sample not found" });
    }
    console.error("Public sample image fetch error:", err.message);
    res.status(400).json({ error: err.message || "Failed to fetch public sample image" });
  }
});

app.post("/api/visual/public-samples/analyze", async (req, res) => {
  try {
    const { sampleId, modelName = "gemini-3.5-flash", includeRequestPreview = false, jsonMode, customInstruction, retryOnInvalidJson = false } = req.body;

    if (!sampleId) return res.status(400).json({ error: "sampleId is required" });

    const sample = getPublicSampleById(sampleId);
    if (!sample) return res.status(404).json({ error: "Sample not found" });

    // Fetch Image Bytes
    const { buffer, mimeType } = await fetchPublicSampleImage(sampleId, "analysis");
    const base64Data = buffer.toString("base64");

    // Prepare Prompt & Options
    const visualCap = getVisualModelCapability(modelName);
    if (visualCap.recommendation === "unsupported") {
      return res.status(400).json({ error: `Model ${modelName} is not supported for visual analysis.` });
    }

    const targetModel = modelName;
    const isGemma = visualCap.providerFamily === "gemma";
    let mode = getStructuredExecutionMode(targetModel);
    
    if (jsonMode === "prompt_only" && mode === "nativeSchema") mode = "promptedJson";
    if (jsonMode === "native_schema" && getModelCapability(targetModel).supportsNativeResponseSchema) mode = "nativeSchema";

    let extractedSchema = null;
    let extractedCustomSchema = false;
    const cap = getModelCapability(targetModel);
    if (cap.supportsNativeResponseSchema && customInstruction) {
      const rawSchema = extractJsonSchemaFromText(customInstruction);
      if (rawSchema) {
        extractedSchema = normalizeSchemaForGemini(rawSchema);
        mode = "nativeSchema";
        extractedCustomSchema = true;
      }
    }

    const isPromptedJson = mode === "promptedJson";

    const systemInstruction = buildVisualAnalysisSystemInstruction();
    const taskPrompt = buildVisualAnalysisTaskPrompt(isPromptedJson) + (customInstruction ? `\n\nUser Instruction: ${customInstruction}` : "");

    let configOption: any = {
      ...VISUAL_ANALYSIS_GENERATION_CONFIG,
      systemInstruction
    };

    if (mode === "nativeSchema") {
      configOption.responseMimeType = "application/json";
      configOption.responseSchema = extractedSchema || VISUAL_ANALYSIS_SCHEMA;
    }

    const runMetadata = buildVisualAnalysisRunMetadata({
      targetModel,
      providerFamily: isGemma ? "gemma" : "gemini",
      visualRecommendation: visualCap.recommendation,
      mode,
      jsonMode,
      customInstructionUsed: !!customInstruction,
      customSchemaUsed: extractedCustomSchema,
      requestPreviewIncluded: includeRequestPreview,
      sourceKind: "publicSample",
      sampleId: sample.id,
      mimeType: mimeType,
      byteLength: buffer.length,
      base64Length: base64Data.length
    });

    const requestPreview = includeRequestPreview ? {
      model: targetModel,
      outputMode: "structured",
      taskPrompt,
      systemInstruction,
      mimeType: mimeType,
      binaryInlineDataUsed: true,
      generationConfig: VISUAL_ANALYSIS_GENERATION_CONFIG
    } : undefined;

    // Call Model
    let aiRes;
    try {
      aiRes = await generateContentWithRetry(targetModel, [
        { inlineData: { data: base64Data, mimeType: mimeType } },
        { text: taskPrompt }
      ], 4, configOption);
    } catch (err: any) {
      const failRes = buildGenerationFailureResponse({
        err,
        targetModel,
        providerFamily: isGemma ? "gemma" : "gemini",
        runMetadata,
        sampleMetadata: {
          id: sample.id,
          title: sample.title,
          category: sample.category,
          licenseKind: sample.source.licenseKind,
          licenseName: sample.source.licenseName,
          attributionText: sample.source.attributionText,
          sourcePageUrl: sample.source.pageUrl
        },
        expectedMetadata: {
          imageKind: sample.expectedImageKind,
          elementCategories: sample.expectedElementCategories,
          elementCategoryAlternatives: sample.expectedElementCategoryAlternatives,
          visibleElementLabels: sample.expectedVisibleElementLabels,
          visibleElementLabelAliases: sample.expectedVisibleElementLabelAliases,
          visibleText: sample.expectedVisibleText,
          notes: sample.expectedNotes
        },
        requestPreview
      });
      return res.status(200).json(failRes); // 200 so UI can handle structured failure
    }

    let outputText = aiRes.text?.trim() || "{}";

    // Parse and Validate
    let parseRes = parseModelJsonOutput(outputText, 1);
    let retryCount = 0;

    if (!parseRes.ok && retryOnInvalidJson) {
      try {
        aiRes = await generateContentWithRetry(targetModel, [
          { inlineData: { data: base64Data, mimeType: mimeType } },
          { text: taskPrompt }
        ], 4, configOption);
        const newOutputText = aiRes.text?.trim() || "{}";
        const newParseRes = parseModelJsonOutput(newOutputText, 2);
        newParseRes.diagnostics.attempts = [...parseRes.diagnostics.attempts, ...newParseRes.diagnostics.attempts];
        parseRes = newParseRes;
        retryCount = 1;
      } catch (retryErr: any) {
        // If recovery model call fails, we stick with the original parse failure and log a diagnostic.
        parseRes.diagnostics.attempts.push({
          requestAttempt: 2,
          mode: "retryFailed",
          success: false,
          errorMessage: "Generation Error: " + retryErr.message
        });
      }
    }

    // Add recovery stats to run metadata
    runMetadata.execution.jsonRecovery = {
      localRecoveryEnabled: true,
      retryOnInvalidJson,
      retryStrategy: "sameRequestOnce",
      retryCount,
      finalParseMode: parseRes.ok ? parseRes.parseMode : undefined
    };

    if (!parseRes.ok) {
      return res.status(500).json({
        success: false,
        error: "Model returned invalid JSON",
        failureKind: "jsonParseError",
        sampleMetadata: {
          id: sample.id,
          title: sample.title,
          category: sample.category,
          licenseKind: sample.source.licenseKind,
          licenseName: sample.source.licenseName,
          attributionText: sample.source.attributionText,
          sourcePageUrl: sample.source.pageUrl
        },
        expectedMetadata: {
          imageKind: sample.expectedImageKind,
          elementCategories: sample.expectedElementCategories,
          elementCategoryAlternatives: sample.expectedElementCategoryAlternatives,
          visibleElementLabels: sample.expectedVisibleElementLabels,
          visibleElementLabelAliases: sample.expectedVisibleElementLabelAliases,
          visibleText: sample.expectedVisibleText,
          notes: sample.expectedNotes
        },
        analysisRun: runMetadata,
        parseDiagnostics: parseRes.diagnostics,
        inputDiagnostics: {
          sourceKind: runMetadata.input.sourceKind,
          sampleId: runMetadata.input.sampleId,
          mimeType: runMetadata.input.mimeType,
          byteLength: runMetadata.input.byteLength,
          base64Length: runMetadata.input.base64Length
        },
        ...(requestPreview ? { requestPreview } : {})
      });
    }

    const parsed = parseRes.parsed;
    const parseDiagnosticsLight = {
      rawOutputLength: parseRes.diagnostics.rawOutputLength,
      attempts: parseRes.diagnostics.attempts,
      parseMode: parseRes.parseMode,
      ...(includeRequestPreview ? { rawOutputPreview: parseRes.diagnostics.rawOutputPreview } : {})
    };

    if (extractedCustomSchema) {
      const result: any = {
        success: true,
        sampleMetadata: {
          id: sample.id,
          title: sample.title,
          category: sample.category,
          licenseKind: sample.source.licenseKind,
          licenseName: sample.source.licenseName,
          attributionText: sample.source.attributionText,
          sourcePageUrl: sample.source.pageUrl
        },
        expectedMetadata: {
          imageKind: sample.expectedImageKind,
          elementCategories: sample.expectedElementCategories,
          elementCategoryAlternatives: sample.expectedElementCategoryAlternatives,
          visibleElementLabels: sample.expectedVisibleElementLabels,
          visibleElementLabelAliases: sample.expectedVisibleElementLabelAliases,
          visibleText: sample.expectedVisibleText,
          notes: sample.expectedNotes
        },
        visualAnalysis: parsed,
        analysisRun: runMetadata,
        parseDiagnostics: parseDiagnosticsLight,
        qualityStatus: "excellent",
        qualityScore: 100,
        qualityIssues: [],
        experimentalModel: false,
        usedModelName: targetModel,
        providerFamily: isGemma ? "gemma" : "gemini",
        effectiveStructuredExecutionMode: mode,
        validationPassed: true,
        schemaVersion: "custom",
        rawOutput: outputText,
        inputDiagnostics: {
          sourceKind: runMetadata.input.sourceKind,
          sampleId: runMetadata.input.sampleId,
          mimeType: runMetadata.input.mimeType,
          byteLength: runMetadata.input.byteLength,
          base64Length: runMetadata.input.base64Length
        }
      };

      if (includeRequestPreview) {
        result.requestPreview = requestPreview;
      }

      return res.json(result);
    }

    const normalized = normalizeVisualAnalysis(parsed);
    const validation = validateVisualAnalysis(normalized);

    let qualityStatus = "invalid";
    let qualityScore = 0;
    let qualityIssues = validation.errors.map(err => ({ code: "SCHEMA_ERROR", message: err, severity: "blocking" }));
    let isExperimental = mode === "promptedJson";

    if (validation.isValid) {
      const qReport = evaluateVisualAnalysisQuality(normalized, {
        modelName: targetModel,
        providerFamily: isGemma ? "gemma" : "gemini",
        effectiveStructuredExecutionMode: mode
      });
      qualityStatus = qReport.status;
      qualityScore = qReport.score;
      qualityIssues = qReport.issues;
      isExperimental = qReport.experimentalModel;
    }

    const result: any = {
      success: validation.isValid,
      sampleMetadata: {
        id: sample.id,
        title: sample.title,
        category: sample.category,
        licenseKind: sample.source.licenseKind,
        licenseName: sample.source.licenseName,
        attributionText: sample.source.attributionText,
        sourcePageUrl: sample.source.pageUrl
      },
      expectedMetadata: {
        imageKind: sample.expectedImageKind,
        elementCategories: sample.expectedElementCategories,
        elementCategoryAlternatives: sample.expectedElementCategoryAlternatives,
        visibleElementLabels: sample.expectedVisibleElementLabels,
        visibleElementLabelAliases: sample.expectedVisibleElementLabelAliases,
        visibleText: sample.expectedVisibleText,
        notes: sample.expectedNotes
      },
      visualAnalysis: normalized,
      analysisRun: runMetadata,
      parseDiagnostics: parseDiagnosticsLight,
      qualityStatus,
      qualityScore,
      qualityIssues,
      experimentalModel: isExperimental,
      usedModelName: targetModel,
      providerFamily: isGemma ? "gemma" : "gemini",
      effectiveStructuredExecutionMode: mode,
      inputDiagnostics: {
        sourceKind: runMetadata.input.sourceKind,
        sampleId: runMetadata.input.sampleId,
        mimeType: runMetadata.input.mimeType,
        byteLength: runMetadata.input.byteLength,
        base64Length: runMetadata.input.base64Length
      }
    };

    if (includeRequestPreview) {
      result.requestPreview = {
        model: targetModel,
        outputMode: "structured",
        taskPrompt,
        systemInstruction,
        mimeType: mimeType,
        binaryInlineDataUsed: true,
        generationConfig: VISUAL_ANALYSIS_GENERATION_CONFIG
      };
    }

    res.json(result);
  } catch (err: any) {
    console.error("Public sample analysis error:", err.message);
    res.status(500).json({ error: err.message || "Failed to analyze public sample" });
  }
});


app.post("/api/drive/debug/analyze-image", async (req, res) => {
  try {
    const { fileId, modelName = "gemini-3.5-flash", customInstruction, includeRequestPreview = false, jsonMode, retryOnInvalidJson = false } = req.body;
    const authHeader = req.headers.authorization;
    if (!authHeader) return res.status(401).json({ error: "Missing Authorization header" });
    const token = authHeader.replace("Bearer ", "");

    if (!fileId) return res.status(400).json({ error: "fileId is required" });

    // 1. Fetch File Metadata
    const metaUrl = `https://www.googleapis.com/drive/v3/files/${fileId}?fields=id,name,mimeType,size,modifiedTime`;
    const metaRes = await fetch(metaUrl, { headers: { Authorization: `Bearer ${token}` } });
    if (!metaRes.ok) {
      return res.status(metaRes.status).json({ error: `Drive API error: ${metaRes.statusText}` });
    }
    const fileMeta = await metaRes.json();

    if (!fileMeta.mimeType.startsWith("image/")) {
      return res.status(400).json({ error: "File must be an image" });
    }

    // 2. Fetch Image Bytes
    const contentUrl = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;
    const fileRes = await fetch(contentUrl, { headers: { Authorization: `Bearer ${token}` } });
    if (!fileRes.ok) {
      return res.status(fileRes.status).json({ error: `Drive media download error: ${fileRes.statusText}` });
    }
    const arrBuffer = await fileRes.arrayBuffer();
    const base64Data = Buffer.from(arrBuffer).toString("base64");

    // 3. Prepare Prompt & Options
    const visualCap = getVisualModelCapability(modelName);
    if (visualCap.recommendation === "unsupported") {
      return res.status(400).json({ error: `Model ${modelName} is not supported for visual analysis.` });
    }

    const targetModel = modelName;
    const isGemma = visualCap.providerFamily === "gemma";
    let mode = getStructuredExecutionMode(targetModel);
    
    if (jsonMode === "prompt_only" && mode === "nativeSchema") mode = "promptedJson";
    if (jsonMode === "native_schema" && getModelCapability(targetModel).supportsNativeResponseSchema) mode = "nativeSchema";

    let extractedSchema = null;
    let extractedCustomSchema = false;
    const cap = getModelCapability(targetModel);
    if (cap.supportsNativeResponseSchema && customInstruction) {
      const rawSchema = extractJsonSchemaFromText(customInstruction);
      if (rawSchema) {
        extractedSchema = normalizeSchemaForGemini(rawSchema);
        mode = "nativeSchema";
        extractedCustomSchema = true;
      }
    }

    // We only support gemini native schema or gemma prompted json for this experiment
    const isPromptedJson = mode === "promptedJson";

    const systemInstruction = buildVisualAnalysisSystemInstruction();
    const taskPrompt = buildVisualAnalysisTaskPrompt(isPromptedJson) + (customInstruction ? `\n\nUser Instruction: ${customInstruction}` : "");

    let configOption: any = { 
      ...VISUAL_ANALYSIS_GENERATION_CONFIG,
      systemInstruction
    };

    if (mode === "nativeSchema") {
      configOption.responseMimeType = "application/json";
      configOption.responseSchema = extractedSchema || VISUAL_ANALYSIS_SCHEMA;
    }

    const runMetadata = buildVisualAnalysisRunMetadata({
      targetModel,
      providerFamily: isGemma ? "gemma" : "gemini",
      visualRecommendation: visualCap.recommendation,
      mode,
      jsonMode,
      customInstructionUsed: !!customInstruction,
      customSchemaUsed: extractedCustomSchema,
      requestPreviewIncluded: includeRequestPreview,
      sourceKind: "driveFile",
      fileId: fileId,
      mimeType: fileMeta.mimeType
    });

    const requestPreview = includeRequestPreview ? {
      model: targetModel,
      outputMode: "structured",
      taskPrompt,
      systemInstruction,
      mimeType: fileMeta.mimeType,
      binaryInlineDataUsed: true,
      generationConfig: VISUAL_ANALYSIS_GENERATION_CONFIG
    } : undefined;

    // 4. Call Model
    let aiRes;
    try {
      aiRes = await generateContentWithRetry(targetModel, [
        { inlineData: { data: base64Data, mimeType: fileMeta.mimeType } },
        { text: taskPrompt }
      ], 4, configOption);
    } catch (err: any) {
      const failRes = buildGenerationFailureResponse({
        err,
        targetModel,
        providerFamily: isGemma ? "gemma" : "gemini",
        runMetadata,
        outputMode: "structured",
        metadata: fileMeta,
        requestPreview
      } as any);
      return res.status(200).json(failRes);
    }

    let outputText = aiRes.text?.trim() || "{}";
    
    // 5. Parse and Validate
    let parseRes = parseModelJsonOutput(outputText, 1);
    let retryCount = 0;

    if (!parseRes.ok && retryOnInvalidJson) {
      try {
        aiRes = await generateContentWithRetry(targetModel, [
          { inlineData: { data: base64Data, mimeType: fileMeta.mimeType } },
          { text: taskPrompt }
        ], 4, configOption);
        const newOutputText = aiRes.text?.trim() || "{}";
        const newParseRes = parseModelJsonOutput(newOutputText, 2);
        newParseRes.diagnostics.attempts = [...parseRes.diagnostics.attempts, ...newParseRes.diagnostics.attempts];
        parseRes = newParseRes;
        retryCount = 1;
      } catch (retryErr: any) {
        parseRes.diagnostics.attempts.push({
          requestAttempt: 2,
          mode: "retryFailed",
          success: false,
          errorMessage: "Generation Error: " + retryErr.message
        });
      }
    }

    // Add recovery stats to run metadata
    runMetadata.execution.jsonRecovery = {
      localRecoveryEnabled: true,
      retryOnInvalidJson,
      retryStrategy: "sameRequestOnce",
      retryCount,
      finalParseMode: parseRes.ok ? parseRes.parseMode : undefined
    };

    if (!parseRes.ok) {
      return res.status(500).json({ 
        success: false,
        outputMode: "structured",
        error: "Model returned invalid JSON", 
        failureKind: "jsonParseError",
        metadata: fileMeta,
        analysisRun: runMetadata,
        parseDiagnostics: parseRes.diagnostics,
        ...(requestPreview ? { requestPreview } : {})
      });
    }

    const parsed = parseRes.parsed;
    const parseDiagnosticsLight = {
      rawOutputLength: parseRes.diagnostics.rawOutputLength,
      attempts: parseRes.diagnostics.attempts,
      parseMode: parseRes.parseMode,
      ...(includeRequestPreview ? { rawOutputPreview: parseRes.diagnostics.rawOutputPreview } : {})
    };

    if (extractedCustomSchema) {
      const result: any = {
        success: true,
        outputMode: "structured",
        metadata: fileMeta,
        visualAnalysis: parsed,
        analysisRun: runMetadata,
        parseDiagnostics: parseDiagnosticsLight,
        qualityStatus: "excellent",
        qualityScore: 100,
        qualityIssues: [],
        experimentalModel: false,
        usedModelName: targetModel,
        providerFamily: isGemma ? "gemma" : "gemini",
        effectiveStructuredExecutionMode: mode,
        validationPassed: true,
        schemaVersion: "custom",
        rawOutput: outputText
      };

      if (includeRequestPreview) {
        result.requestPreview = {
          model: targetModel,
          outputMode: "structured",
          taskPrompt,
          systemInstruction,
          mimeType: fileMeta.mimeType,
          binaryInlineDataUsed: true,
          generationConfig: VISUAL_ANALYSIS_GENERATION_CONFIG
        };
      }

      return res.json(result);
    }

    const normalized = normalizeVisualAnalysis(parsed);
    const validation = validateVisualAnalysis(normalized);
    
    let qualityStatus = "invalid";
    let qualityScore = 0;
    let qualityIssues = validation.errors.map(err => ({ code: "SCHEMA_ERROR", message: err, severity: "blocking" }));
    let isExperimental = mode === "promptedJson";

    if (validation.isValid) {
      const qReport = evaluateVisualAnalysisQuality(normalized, {
        modelName: targetModel,
        providerFamily: isGemma ? "gemma" : "gemini",
        effectiveStructuredExecutionMode: mode
      });
      qualityStatus = qReport.status;
      qualityScore = qReport.score;
      qualityIssues = qReport.issues;
      isExperimental = qReport.experimentalModel;
    }

    const result: any = {
      success: validation.isValid,
      outputMode: "structured",
      metadata: fileMeta,
      visualAnalysis: normalized,
      analysisRun: runMetadata,
      parseDiagnostics: parseDiagnosticsLight,
      qualityStatus,
      qualityScore,
      qualityIssues,
      experimentalModel: isExperimental,
      usedModelName: targetModel,
      providerFamily: isGemma ? "gemma" : "gemini",
      effectiveStructuredExecutionMode: mode
    };

    if (includeRequestPreview) {
      result.requestPreview = {
        model: targetModel,
        outputMode: "structured",
        taskPrompt,
        systemInstruction,
        mimeType: fileMeta.mimeType,
        binaryInlineDataUsed: true,
        generationConfig: VISUAL_ANALYSIS_GENERATION_CONFIG
      };
    }

    // Immediate debug response only. Do not cache or persist.
    res.json(result);
  } catch (err: any) {
    console.error("Image analysis error:", err);
    res.status(500).json({ error: err.message || "Failed to process image" });
  }
});

app.get("/api/cache/stats", async (req, res) => {
  const stats = await getCacheMetricsResponse({
    scan: SCAN_CACHE_DIR,
    snippets: CACHE_DIR,
    summaries: SUMMARIES_CACHE_DIR,
    experimentHistory: EXPERIMENT_HISTORY_DIR
  });
  res.json(stats);
});

app.post("/api/cache/stats/reset", (req, res) => {
  resetCacheMetrics();
  res.json({ success: true });
});

// 5. Mount Vite middleware for serving frontend SPA assets or dev server
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    // SPA fallback handling
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Drive Indexer Backend] Running on http://localhost:${PORT}`);
  });
}

if (process.env.NODE_ENV !== "test") {
  startServer();
}
