import React, { useState, useMemo, useEffect, useCallback } from 'react';
import { 
  FileText, Search, RefreshCw, Clipboard, Check, 
  Folder, AlertTriangle, Play, HelpCircle, Loader2, Copy, AlertCircle, FileCode
} from 'lucide-react';
import { db, collection, getDocs, query, limit } from '../lib/firebase';
import { getSummaryMetadataStatus, getSummaryMetadataStatusReasons } from '../lib/summaryMetadata';
import { SUMMARY_ANALYSIS_PROMPT_VERSION, SUMMARY_DEBUG_SYSTEM_INSTRUCTION_VERSION } from '../lib/promptSpecs';
import { SCHEMA_VERSION_V12 } from '../lib/summaryAnalysis/schema';
import { getStructuredSummaryDisplaySummary } from '../lib/summaryAnalysis/versioned';
import { 
  sortSavedSummariesByGeneratedAt, 
  filterSavedSummaries, 
  getDocumentTypeOptions, 
  getSubjectAreaOptions, 
  sanitizeSavedSummaryForClipboard 
} from '../lib/savedSummaryBrowser';
import { buildReadOnlyIndexMdPreview } from '../lib/indexMdPreview';
import { mergeIndexMdAutoGeneratedBlock, HybridMergeResult } from '../lib/indexMdHybridMerge';
import { runIndexMdPreflight, IndexMdPreflightResult, IndexMdCandidate } from '../lib/indexMdPreflight';

interface SavedSummariesBrowserProps {
  userId: string | undefined;
  token: string | null;
  dirs: any[];
  setActiveTab?: (tabId: any) => void;
  // Optional jump-to-test helpers if we still want that functionality
  onSelectToTest?: (fileId: string) => void;
}

export const SavedSummariesBrowser: React.FC<SavedSummariesBrowserProps> = ({
  userId,
  token,
  dirs,
  setActiveTab,
  onSelectToTest,
}) => {
  const [savedSummaries, setSavedSummaries] = useState<any[]>([]);
  const [loadingSaved, setLoadingSaved] = useState(false);
  const [savedError, setSavedError] = useState<string | null>(null);

  const fetchSavedSummaries = useCallback(async () => {
    if (!userId) return;
    setLoadingSaved(true);
    setSavedError(null);
    try {
      const colRef = collection(db, "users", userId, "file_summaries");
      const q = query(colRef, limit(100)); // Increased limit slightly for browser
      const snap = await getDocs(q);
      const list = snap.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      }));
      setSavedSummaries(list);
    } catch (err: any) {
      console.error("Failed to fetch saved summaries:", err);
      setSavedError(err.message || String(err));
    } finally {
      setLoadingSaved(false);
    }
  }, [userId]);

  useEffect(() => {
    fetchSavedSummaries();
  }, [fetchSavedSummaries]);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [typeFilter, setTypeFilter] = useState<string>('all');
  const [subjectFilter, setSubjectFilter] = useState<string>('all');
  const [selectedDirId, setSelectedDirId] = useState<string>('');
  
  // Selection state for detail inspector
  const [selectedSummaryId, setSelectedSummaryId] = useState<string | null>(null);

  // Copy states
  const [copiedIndexMd, setCopiedIndexMd] = useState(false);
  const [copiedJsonId, setCopiedJsonId] = useState<string | null>(null);
  const [copiedOneLineId, setCopiedOneLineId] = useState<string | null>(null);
  const [copiedPreviewId, setCopiedPreviewId] = useState<string | null>(null);

  // Dry-run merge states
  const [existingIndexMd, setExistingIndexMd] = useState<string>('');
  const [allowAppendIfMissing, setAllowAppendIfMissing] = useState<boolean>(false);
  const [mergeResult, setMergeResult] = useState<HybridMergeResult | null>(null);
  const [copiedMergedMarkdown, setCopiedMergedMarkdown] = useState<boolean>(false);
  const [copiedDiagnostics, setCopiedDiagnostics] = useState<boolean>(false);

  // Preflight states
  const [isPreflightLoading, setIsPreflightLoading] = useState(false);
  const [preflightResult, setPreflightResult] = useState<IndexMdPreflightResult | null>(null);
  const [preflightError, setPreflightError] = useState<string | null>(null);

  const handleFetchIndexMdPreflight = async () => {
    if (!selectedSummaryId || !token) return;
    const summary = processedSummaries.find(s => s.id === selectedSummaryId);
    if (!summary || !summary.parentId) {
      setPreflightError("選択されたサマリーに親フォルダ情報（parentId）がありません。");
      return;
    }

    setIsPreflightLoading(true);
    setPreflightError(null);
    setPreflightResult(null);

    try {
      // 1. Lookup index.md candidates
      const lookupRes = await fetch(`/api/drive/index-preflight/lookup?folderId=${summary.parentId}`, {
        headers: {
          'x-google-drive-token': token
        }
      });
      if (!lookupRes.ok) {
        const errData = await lookupRes.json();
        throw new Error(errData.error || 'Lookup failed');
      }
      const { candidates } = await lookupRes.json();

      let existingContent: string | null = null;
      if (candidates.length === 1) {
        // 2. Fetch content read-only
        const contentRes = await fetch(`/api/drive/index-preflight/content?fileId=${candidates[0].fileId}`, {
          headers: {
            'x-google-drive-token': token
          }
        });
        if (contentRes.ok) {
          const { content } = await contentRes.json();
          existingContent = content;
          setExistingIndexMd(content); // Sync with manual editor for convenience
        } else {
          // If we can't read, it's a read error for the preflight
          existingContent = null;
        }
      }

      // 3. Run preflight logic
      const result = runIndexMdPreflight({
        candidates,
        existingMarkdown: existingContent,
        generatedMarkdown: generatedIndexMd,
        allowAppendIfMissing
      });

      setPreflightResult(result);
      if (result.mergedMarkdown && result.status === 'merge-ready') {
        // Automatically update the main mergeResult for display if successful
        setMergeResult({
          status: result.mergeStatus as any,
          mergedMarkdown: result.mergedMarkdown,
          diagnostics: result.diagnostics,
          preservedUserContent: result.preservedUserContent || false,
          changed: result.changed || false
        });
      }
    } catch (err: any) {
      console.error(err);
      setPreflightError(err.message || "プレバイフライト中にエラーが発生しました。");
    } finally {
      setIsPreflightLoading(false);
    }
  };

  const handleClearPreflight = () => {
    setPreflightResult(null);
    setPreflightError(null);
    setExistingIndexMd('');
    setMergeResult(null);
  };

  const handleRunDryRunMerge = () => {
    if (!generatedIndexMd) return;
    const result = mergeIndexMdAutoGeneratedBlock(existingIndexMd, generatedIndexMd, {
      allowAppendIfMissing
    });
    setMergeResult(result);
  };

  const handleSetSampleExistingMd = () => {
    setExistingIndexMd(`# Project Documentation Folder

This is a custom user-written introduction explaining the repository contents.
We want this custom paragraph to be preserved completely after the merge operation!

<!-- AUTO_GENERATED_START -->
## AI Summary
Old stale generated block that will be completely overwritten by the new generator.
<!-- AUTO_GENERATED_END -->

## Development Setup Notes
Here are user-authored instructions on how to build, run and deploy this project.
These notes must also be completely preserved intact!`);
    setMergeResult(null);
  };

  // Compute computedStatus and sort summaries by generatedAt
  const processedSummaries = useMemo(() => {
    const enriched = savedSummaries.map(item => {
      const status = getSummaryMetadataStatus({
        savedMetadata: item,
        currentSchemaVersion: SCHEMA_VERSION_V12,
        currentPromptVersion: SUMMARY_ANALYSIS_PROMPT_VERSION,
        currentSystemInstructionVersion: SUMMARY_DEBUG_SYSTEM_INSTRUCTION_VERSION,
        currentFileModifiedTime: item.modifiedTime // Assume no modification drift by default
      });
      return {
        ...item,
        computedStatus: status
      };
    });
    return sortSavedSummariesByGeneratedAt(enriched);
  }, [savedSummaries]);

  // Unique document types list for filtering
  const docTypes = useMemo(() => {
    return getDocumentTypeOptions(processedSummaries);
  }, [processedSummaries]);

  // Unique subject areas list for filtering
  const subjectAreasList = useMemo(() => {
    return getSubjectAreaOptions(processedSummaries);
  }, [processedSummaries]);

  // Filtered summaries list
  const filteredSummaries = useMemo(() => {
    return filterSavedSummaries(processedSummaries, searchTerm, statusFilter, typeFilter, subjectFilter);
  }, [processedSummaries, searchTerm, statusFilter, typeFilter, subjectFilter]);

  // Currently selected summary object
  const selectedSummary = useMemo(() => {
    if (!selectedSummaryId) return null;
    return processedSummaries.find(item => item.id === selectedSummaryId) || null;
  }, [processedSummaries, selectedSummaryId]);

  // Generate status reasons for the selected summary
  const selectedSummaryReasons = useMemo(() => {
    if (!selectedSummary) return [];
    return getSummaryMetadataStatusReasons({
      savedMetadata: selectedSummary,
      currentSchemaVersion: SCHEMA_VERSION_V12,
      currentPromptVersion: SUMMARY_ANALYSIS_PROMPT_VERSION,
      currentSystemInstructionVersion: SUMMARY_DEBUG_SYSTEM_INSTRUCTION_VERSION,
      currentFileModifiedTime: selectedSummary.modifiedTime
    });
  }, [selectedSummary]);

  // ⚡ Bolt: Pre-calculate file counts per directory to optimize O(N) rendering performance
  const fileCountsByDir = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const item of processedSummaries) {
      if (item.parentId) {
        counts[item.parentId] = (counts[item.parentId] || 0) + 1;
      }
    }
    return counts;
  }, [processedSummaries]);

  // ⚡ Bolt: Memoize filtered files for selected directory to avoid recalculating on every render
  const filesInSelectedDir = useMemo(() => {
    if (!selectedDirId) return [];
    return processedSummaries.filter(item => item.parentId === selectedDirId);
  }, [processedSummaries, selectedDirId]);

  // ⚡ Bolt: Memoize expensive topic extraction map/set operation
  const selectedDirMainTopics = useMemo(() => {
    if (filesInSelectedDir.length === 0) return '一般事務';
    return Array.from(new Set(filesInSelectedDir.flatMap(f => f.structured?.topics || []))).slice(0, 5).join('、') || '一般事務';
  }, [filesInSelectedDir]);

  // Directory-wise index.md Auto-Generated code builder (Read-Only Preview)
  const generatedIndexMd = useMemo(() => {
    if (!selectedDirId) return '';
    const folder = dirs.find(d => d.drive_id === selectedDirId);
    const folderName = folder ? (folder.path || folder.name) : 'Selected Directory';

    // Render index.md via our pure deterministic preview helper
    return buildReadOnlyIndexMdPreview({
      folderName,
      filesInFolder: filesInSelectedDir,
      nowIso: new Date().toISOString(),
      promptVersion: SUMMARY_ANALYSIS_PROMPT_VERSION
    });
  }, [selectedDirId, dirs, filesInSelectedDir]);

  const handleCopyIndexMd = async () => {
    if (!generatedIndexMd) return;
    try {
      await navigator.clipboard.writeText(generatedIndexMd);
      setCopiedIndexMd(true);
      setTimeout(() => setCopiedIndexMd(false), 2000);
    } catch (err) {
      console.error(err);
    }
  };

  const handleCopyJson = async (item: any) => {
    try {
      const safeJson = sanitizeSavedSummaryForClipboard(item);
      await navigator.clipboard.writeText(JSON.stringify(safeJson, null, 2));
      setCopiedJsonId(item.id);
      setTimeout(() => setCopiedJsonId(null), 2000);
    } catch (err) {
      console.error(err);
    }
  };

  const handleCopyOneLineSummary = async (item: any) => {
    const text = getStructuredSummaryDisplaySummary(item.structured) || item.summary || '';
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      setCopiedOneLineId(item.id);
      setTimeout(() => setCopiedOneLineId(null), 2000);
    } catch (err) {
      console.error(err);
    }
  };

  const handleSelectToTest = (item: any) => {
    try {
      localStorage.setItem('gemini_selected_file_id', item.fileId);
    } catch (e) {
      // Silent
    }
    if (onSelectToTest) {
      onSelectToTest(item.fileId);
    }
    if (setActiveTab) {
      setActiveTab("summary-debugger");
    }
  };

  return (
    <div className="space-y-6">
      {/* Search and Filters panel */}
      <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <h3 className="font-semibold text-slate-800 flex items-center gap-2 text-base">
            <FileText className="w-5 h-5 text-indigo-600" />
            保存済み要約ブラウザ
          </h3>
          <button
            onClick={fetchSavedSummaries}
            disabled={loadingSaved}
            className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded text-xs transition-all flex items-center justify-center gap-1.5 shadow-sm self-end sm:self-auto"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loadingSaved ? "animate-spin" : ""}`} />
            データを更新
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3">
          {/* Search Input */}
          <div className="relative">
            <span className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <Search className="w-4 h-4 text-slate-400" />
            </span>
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="ファイル名、要約内容、モデル..."
              className="w-full bg-slate-50 border border-slate-200 rounded-md pl-9 pr-3 py-2 text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 text-slate-800"
            />
          </div>

          {/* Status Filter */}
          <div className="flex items-center gap-2">
            <span className="text-xs font-medium text-slate-500 shrink-0">ステータス:</span>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 rounded-md p-2 text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 text-slate-800"
            >
              <option value="all">すべて (All)</option>
              <option value="current">最新状態 (Current)</option>
              <option value="stale-schema">スキーマが古い (Stale Schema)</option>
              <option value="stale-prompt">プロンプトが古い (Stale Prompt)</option>
              <option value="stale-file">ファイル更新あり (Stale File)</option>
              <option value="invalid">無効データ (Invalid)</option>
            </select>
          </div>

          {/* Doc Type Filter */}
          <div className="flex items-center gap-2">
            <span className="text-xs font-medium text-slate-500 shrink-0">分類:</span>
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 rounded-md p-2 text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 text-slate-800"
            >
              <option value="all">すべての分類</option>
              {docTypes.map(t => (
                <option key={t} value={t}>{t}</option>
              ))}
            </select>
          </div>

          {/* Subject Area Filter */}
          <div className="flex items-center gap-2">
            <span className="text-xs font-medium text-slate-500 shrink-0">分野:</span>
            <select
              value={subjectFilter}
              onChange={(e) => setSubjectFilter(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 rounded-md p-2 text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 text-slate-800"
            >
              <option value="all">すべての分野</option>
              {subjectAreasList.map(s => (
                <option key={s} value={s}>{s}</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Directory-wise Read-Only Preview Panel */}
      <div className="bg-indigo-950/5 border border-indigo-200/60 p-5 rounded-lg space-y-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Folder className="w-5 h-5 text-indigo-600" />
            <h4 className="font-semibold text-slate-800 text-sm">
              📁 ディレクトリ別 index.md プレビュー
            </h4>
            <span className="inline-flex items-center bg-indigo-100 text-indigo-800 text-[10px] px-2 py-0.5 rounded border border-indigo-200 font-bold">
              読込専用デモ (Read-Only / Preview)
            </span>
          </div>
          <p className="text-xs text-slate-500">
            スキャンされたディレクトリを選択すると、該当フォルダに保存された要約データから、将来生成される予定の `index.md` ファイルのレイアウトをローカルプレビューします。<span className="text-indigo-700 font-semibold">（Driveファイルへの書き込みは一切行いません：Driveには書き込みません）</span>
          </p>
        </div>

        <div className="max-w-md">
          <select
            value={selectedDirId}
            onChange={(e) => setSelectedDirId(e.target.value)}
            className="w-full bg-white border border-slate-200 rounded-md p-2 text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 text-slate-800"
          >
            <option value="">-- ディレクトリを選択して要約をプレビュー --</option>
            {dirs.map((dir) => {
              const fileCount = fileCountsByDir[dir.drive_id] || 0;
              return (
                <option key={dir.drive_id} value={dir.drive_id}>
                  {dir.path || dir.name} ({fileCount}件の要約ファイル)
                </option>
              );
            })}
          </select>
        </div>

        {selectedDirId && (
          <div className="space-y-3 mt-3">
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-bold text-indigo-900 uppercase tracking-wider bg-indigo-100/60 px-2 py-1 rounded">
                読込専用プレビュー（index.md 生成候補）- Driveには書き込みません
              </span>
              <button
                onClick={handleCopyIndexMd}
                disabled={!generatedIndexMd}
                className={`px-2.5 py-1 text-xs rounded border transition-all flex items-center gap-1 font-bold ${
                  copiedIndexMd 
                    ? "bg-emerald-50 text-emerald-700 border-emerald-200" 
                    : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50"
                }`}
              >
                {copiedIndexMd ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Clipboard className="w-3.5 h-3.5" />}
                {copiedIndexMd ? "コピーしました" : "Markdownをコピー"}
              </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              {/* Visual render mockup */}
              <div className="bg-white border border-slate-200 rounded-lg p-4 shadow-sm prose prose-sm max-w-none text-slate-800">
                <div className="border-b border-rose-100 bg-rose-50/50 p-2 rounded text-[10px] text-rose-700 font-bold mb-3 flex items-center gap-1">
                  <AlertTriangle className="w-3.5 h-3.5 text-rose-500 shrink-0" />
                  実ファイルへの影響はありません。これはFirestore内の要約から構築された読込専用プレビューです。
                </div>
                
                <div className="space-y-4">
                  <div>
                    <h2 className="text-xs font-extrabold text-slate-900 border-b border-slate-100 pb-1 flex items-center gap-1 uppercase tracking-wider">
                      AI Summary
                    </h2>
                    <p className="text-xs text-slate-600 mt-1 leading-relaxed">
                      {filesInSelectedDir.length > 0
                        ? `このディレクトリには ${filesInSelectedDir.length} 件の要約済み重要ドキュメントが配置されています。主要テーマは ${selectedDirMainTopics} です。`
                        : "保存されている要約ファイルはありません。"}
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xs font-extrabold text-slate-900 border-b border-slate-100 pb-1 uppercase tracking-wider">
                      Files
                    </h2>
                    {filesInSelectedDir.length > 0 ? (
                      <ul className="space-y-2 mt-2 list-none pl-0">
                        {filesInSelectedDir.map(file => {
                              let badgeText = "";
                              let badgeColor = "bg-slate-100 text-slate-600";
                              if (file.computedStatus === "stale-schema") {
                                badgeText = "スキーマ古";
                                badgeColor = "bg-amber-100 text-amber-800";
                              } else if (file.computedStatus === "stale-prompt") {
                                badgeText = "プロンプト古";
                                badgeColor = "bg-amber-100 text-amber-800";
                              } else if (file.computedStatus === "stale-file") {
                                badgeText = "更新あり";
                                badgeColor = "bg-amber-100 text-amber-800";
                              } else if (file.computedStatus === "invalid") {
                                badgeText = "無効";
                                badgeColor = "bg-rose-100 text-rose-800";
                              }

                              return (
                                <li key={file.fileId} className="border-l-2 border-indigo-400 pl-3 py-1 bg-slate-50 rounded-r">
                                  <span className="font-semibold text-xs text-indigo-950 block">
                                    {file.fileName || "名称未設定"}
                                    {badgeText && (
                                      <span className={`ml-2 text-[9px] px-1.5 py-0.2 rounded font-bold ${badgeColor}`}>
                                        {badgeText}
                                      </span>
                                    )}
                                  </span>
                                  <span className="text-xs text-slate-600 leading-relaxed block mt-0.5">
                                    {getStructuredSummaryDisplaySummary(file.structured) || file.summary}
                                  </span>
                                </li>
                              );
                            })}
                          </ul>
                        ) : (
                          <p className="text-xs text-slate-400 italic mt-1">直接配置された要約済みファイルはありません。</p>
                        )}
                      </div>

                      <div>
                        <h2 className="text-xs font-extrabold text-slate-900 border-b border-slate-100 pb-1 uppercase tracking-wider">
                          Subdirectories
                        </h2>
                        <p className="text-xs text-slate-400 italic mt-1">サブディレクトリ構造は将来のインデックス処理で結合されます。</p>
                      </div>
                    </div>
              </div>

              {/* Source code block */}
              <div className="bg-slate-900 border border-slate-800 rounded-lg overflow-hidden flex flex-col h-full shadow-lg">
                <div className="bg-slate-800 px-3 py-2 border-b border-slate-700 flex items-center justify-between">
                  <span className="text-[10px] font-mono text-slate-400">index.md Markdown Source Code</span>
                </div>
                <textarea
                  readOnly
                  value={generatedIndexMd}
                  className="bg-slate-950 text-slate-300 font-mono text-xs p-4 focus:outline-none flex-1 min-h-[250px] leading-relaxed resize-none"
                />
              </div>
            </div>

            {/* Part B: Hybrid index.md Merge Preview (Dry-run) */}
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-5 mt-6 space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-200 pb-3">
                <div className="space-y-1">
                  <h4 className="font-semibold text-slate-800 flex items-center gap-2 text-sm">
                    <FileCode className="w-5 h-5 text-indigo-600" />
                    ハイブリッド index.md マージ・プレビュー (Dry-run)
                  </h4>
                  <p className="text-xs text-slate-500">
                    既存の index.md の記述と、自動生成された AI 要約ブロックを安全にマージする動作検証エンジンです。
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <span className="bg-rose-50 border border-rose-200 text-rose-700 text-[10px] font-bold px-2.5 py-1 rounded shrink-0">
                    シミュレーション専用
                  </span>
                  <span className="bg-slate-100 border border-slate-200 text-slate-600 text-[10px] font-bold px-2.5 py-1 rounded shrink-0">
                    Driveには書き込みません
                  </span>
                </div>
              </div>

              {/* Part C: Drive-connected read-only preflight */}
              <div className="bg-white border border-indigo-100 rounded-lg p-4 shadow-sm space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="p-1.5 bg-indigo-50 rounded">
                      <RefreshCw className={`w-4 h-4 text-indigo-600 ${isPreflightLoading ? 'animate-spin' : ''}`} />
                    </div>
                    <div>
                      <h5 className="text-xs font-bold text-slate-800">Drive 連携型 読み取り専用プレフライト</h5>
                      <p className="text-[10px] text-slate-500">フォルダ内の既存 index.md を自動検出してマージを検証します。</p>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    {preflightResult && (
                      <button
                        onClick={handleClearPreflight}
                        className="text-[10px] font-bold text-slate-400 hover:text-slate-600 px-2 py-1"
                      >
                        結果をクリア
                      </button>
                    )}
                    <button
                      onClick={handleFetchIndexMdPreflight}
                      disabled={isPreflightLoading || !token}
                      className="px-4 py-1.5 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-300 text-white font-bold rounded text-[11px] transition-colors flex items-center gap-1.5 shadow-sm"
                    >
                      {isPreflightLoading ? (
                        <Loader2 className="w-3 h-3 animate-spin" />
                      ) : (
                        <Search className="w-3 h-3" />
                      )}
                      既存 index.md を読み取り専用で取得
                    </button>
                  </div>
                </div>

                {preflightError && (
                  <div className="bg-rose-50 border border-rose-100 p-2 rounded flex items-start gap-2 text-rose-700 text-[10px]">
                    <AlertTriangle className="w-3.5 h-3.5 shrink-0" />
                    <span>{preflightError}</span>
                  </div>
                )}

                {preflightResult && (
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-1">
                    <div className="bg-slate-50 p-2 rounded border border-slate-100 space-y-1">
                      <span className="text-[9px] font-bold text-slate-400 uppercase">Preflight Status</span>
                      <div className="flex items-center gap-1.5">
                        {(() => {
                          switch (preflightResult.status) {
                            case "existing-index-found":
                            case "merge-ready":
                              return <Check className="w-3.5 h-3.5 text-emerald-600" />;
                            case "missing-index":
                              return <HelpCircle className="w-3.5 h-3.5 text-indigo-500" />;
                            default:
                              return <AlertCircle className="w-3.5 h-3.5 text-rose-500" />;
                          }
                        })()}
                        <span className="text-[11px] font-bold text-slate-700">{preflightResult.status}</span>
                      </div>
                    </div>

                    <div className="bg-slate-50 p-2 rounded border border-slate-100 space-y-1">
                      <span className="text-[9px] font-bold text-slate-400 uppercase">File Info</span>
                      {preflightResult.candidate ? (
                        <div className="space-y-0.5">
                          <p className="text-[10px] font-mono text-slate-600 truncate" title={preflightResult.candidate.fileId}>
                            ID: {preflightResult.candidate.fileId}
                          </p>
                          <p className="text-[9px] text-slate-400">
                            Modified: {preflightResult.candidate.modifiedTime ? new Date(preflightResult.candidate.modifiedTime).toLocaleString() : 'N/A'}
                          </p>
                        </div>
                      ) : (
                        <p className="text-[10px] text-slate-400 italic">No existing file found</p>
                      )}
                    </div>

                    <div className="bg-slate-50 p-2 rounded border border-slate-100 space-y-1">
                      <span className="text-[9px] font-bold text-slate-400 uppercase">Write Readiness</span>
                      <div className="flex items-center gap-1.5">
                        <span className={`text-[11px] font-bold ${preflightResult.canProceedToFutureWrite ? 'text-emerald-700' : 'text-rose-700'}`}>
                          {preflightResult.canProceedToFutureWrite ? '🟢 READY (Future Write)' : '🔴 BLOCKED'}
                        </span>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
                {/* Left side: Existing markdown editor & trigger */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-slate-600 flex items-center gap-1">
                      既存の index.md 記述
                    </span>
                    <button
                      onClick={handleSetSampleExistingMd}
                      className="text-[10px] font-bold text-indigo-600 hover:text-indigo-700 hover:underline"
                    >
                      テスト用サンプルを読み込む
                    </button>
                  </div>
                  <textarea
                    value={existingIndexMd}
                    onChange={(e) => setExistingIndexMd(e.target.value)}
                    placeholder="ここに既存の index.md の内容をペーストするか、サンプルの読み込みリンクをクリックしてください..."
                    className="w-full bg-white border border-slate-200 rounded-md p-3 font-mono text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 h-[220px]"
                  />

                  <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
                    <label className="inline-flex items-center gap-2 cursor-pointer text-xs text-slate-600 select-none">
                      <input
                        type="checkbox"
                        checked={allowAppendIfMissing}
                        onChange={(e) => setAllowAppendIfMissing(e.target.checked)}
                        className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                      />
                      <span>マーカー不在時はファイルの末尾に追記する (allowAppendIfMissing)</span>
                    </label>

                    <button
                      onClick={handleRunDryRunMerge}
                      className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded text-xs transition-colors flex items-center justify-center gap-1.5 shadow-sm"
                    >
                      <Play className="w-3.5 h-3.5" />
                      マージのシミュレーションを実行
                    </button>
                  </div>
                </div>

                {/* Right side: Merged result preview */}
                <div className="space-y-3">
                  <span className="text-xs font-bold text-slate-600 block">
                    マージシミュレーション結果
                  </span>

                  {!mergeResult ? (
                    <div className="border border-dashed border-slate-200 rounded-lg p-8 text-center text-slate-400 h-[220px] flex flex-col items-center justify-center space-y-2 bg-white/50">
                      <HelpCircle className="w-8 h-8 stroke-1" />
                      <p className="text-xs font-semibold">シミュレーションが未実行です</p>
                      <p className="text-[10px]">「マージのシミュレーションを実行」ボタンをクリックして結果を確認してください。</p>
                    </div>
                  ) : (
                    <div className="space-y-3 h-[220px] flex flex-col justify-between">
                      <div className="bg-white border border-slate-200 rounded-lg p-3 space-y-2 text-[11px] overflow-y-auto flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="font-bold text-slate-500">ステータス:</span>
                          {(() => {
                            switch (mergeResult.status) {
                              case "replaced-existing-block":
                                return (
                                  <span className="bg-emerald-50 text-emerald-700 border border-emerald-200 px-2 py-0.5 rounded font-bold text-[10px]">
                                    ブロック置換成功 (replaced-existing-block)
                                  </span>
                                );
                              case "appended-new-block":
                                return (
                                  <span className="bg-indigo-50 text-indigo-700 border border-indigo-200 px-2 py-0.5 rounded font-bold text-[10px]">
                                    新規末尾追記 (appended-new-block)
                                  </span>
                                );
                              case "missing-start-marker":
                                return (
                                  <span className="bg-rose-50 text-rose-700 border border-rose-200 px-2 py-0.5 rounded font-bold text-[10px]">
                                    開始マーカー欠落 (missing-start-marker)
                                  </span>
                                );
                              case "missing-end-marker":
                                return (
                                  <span className="bg-rose-50 text-rose-700 border border-rose-200 px-2 py-0.5 rounded font-bold text-[10px]">
                                    終了マーカー欠落 (missing-end-marker)
                                  </span>
                                );
                              case "malformed-marker-order":
                                return (
                                  <span className="bg-rose-50 text-rose-700 border border-rose-200 px-2 py-0.5 rounded font-bold text-[10px]">
                                    マーカー順序不正 (malformed-marker-order)
                                  </span>
                                );
                              case "empty-generated-content":
                                return (
                                  <span className="bg-amber-50 text-amber-700 border border-amber-200 px-2 py-0.5 rounded font-bold text-[10px]">
                                    コンテンツ空 (empty-generated-content)
                                  </span>
                                );
                              default:
                                return (
                                  <span className="bg-slate-100 text-slate-600 border border-slate-200 px-2 py-0.5 rounded font-bold text-[10px]">
                                    不明
                                  </span>
                                );
                            }
                          })()}
                        </div>

                        <div className="grid grid-cols-2 gap-2 text-[10px] text-slate-500">
                          <div>
                            <span>手書きコンテンツ維持:</span>
                            <span className="font-bold text-slate-800 ml-1.5">
                              {mergeResult.preservedUserContent ? "🟢 はい" : "🔴 いいえ"}
                            </span>
                          </div>
                          <div>
                            <span>内容の変更検知:</span>
                            <span className="font-bold text-slate-800 ml-1.5">
                              {mergeResult.changed ? "🟢 変更あり" : "⚪️ 変更なし"}
                            </span>
                          </div>
                        </div>

                        {mergeResult.diagnostics.length > 0 && (
                          <div className="bg-amber-50/50 border border-amber-100 rounded p-2 text-[10px] text-amber-800 space-y-1">
                            <span className="font-bold block">診断ログ・警告:</span>
                            <ul className="list-disc pl-4 space-y-0.5">
                              {mergeResult.diagnostics.map((d, idx) => (
                                <li key={idx}>{d}</li>
                              ))}
                            </ul>
                          </div>
                        )}
                      </div>

                      <div className="flex gap-2">
                        <button
                          onClick={async () => {
                            try {
                              await navigator.clipboard.writeText(mergeResult.mergedMarkdown);
                              setCopiedMergedMarkdown(true);
                              setTimeout(() => setCopiedMergedMarkdown(false), 2000);
                            } catch (err) {
                              console.error(err);
                            }
                          }}
                          className={`px-3 py-1.5 text-xs rounded border transition-all flex items-center gap-1 font-bold ${
                            copiedMergedMarkdown
                              ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                              : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50"
                          }`}
                        >
                          {copiedMergedMarkdown ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Clipboard className="w-3.5 h-3.5" />}
                          {copiedMergedMarkdown ? "マージ結果コピー済" : "マージ結果をコピー"}
                        </button>

                        {mergeResult.diagnostics.length > 0 && (
                          <button
                            onClick={async () => {
                              try {
                                await navigator.clipboard.writeText(mergeResult.diagnostics.join("\n"));
                                setCopiedDiagnostics(true);
                                setTimeout(() => setCopiedDiagnostics(false), 2000);
                              } catch (err) {
                                console.error(err);
                              }
                            }}
                            className={`px-3 py-1.5 text-xs rounded border transition-all flex items-center gap-1 font-bold ${
                              copiedDiagnostics
                                ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                                : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50"
                            }`}
                          >
                            {copiedDiagnostics ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Clipboard className="w-3.5 h-3.5" />}
                            {copiedDiagnostics ? "ログコピー済" : "診断ログをコピー"}
                          </button>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {mergeResult && mergeResult.mergedMarkdown && (
                <div className="bg-slate-900 border border-slate-800 rounded-lg overflow-hidden flex flex-col shadow-lg mt-3">
                  <div className="bg-slate-800 px-3 py-2 border-b border-slate-700 flex items-center justify-between">
                    <span className="text-[10px] font-mono text-slate-400">マージ後の index.md プレビュー（想定出力）</span>
                  </div>
                  <textarea
                    readOnly
                    value={mergeResult.mergedMarkdown}
                    className="bg-slate-950 text-slate-300 font-mono text-xs p-4 focus:outline-none min-h-[180px] max-h-[300px] leading-relaxed resize-none"
                  />
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Grid containing master table and metadata detail inspector */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Summaries List Table */}
        <div className="bg-white rounded-lg border border-slate-200 shadow-sm overflow-hidden lg:col-span-7">
          <div className="px-5 py-4 border-b border-slate-200 bg-slate-50/50 flex items-center justify-between">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider font-mono">
              Firestore 保存レコード: {filteredSummaries.length} / {savedSummaries.length} 件
            </span>
          </div>

          {loadingSaved ? (
            <div className="p-12 flex flex-col items-center justify-center gap-3">
              <Loader2 className="w-8 h-8 text-indigo-600 animate-spin" />
              <p className="text-sm text-slate-500">保存済み要約データをロード中...</p>
            </div>
          ) : savedError ? (
            <div className="p-8 text-center space-y-2">
              <p className="text-rose-500 font-semibold text-sm">データの読み込みに失敗しました</p>
              <p className="text-xs text-slate-500">{savedError}</p>
            </div>
          ) : filteredSummaries.length === 0 ? (
            <div className="p-12 text-center space-y-2 text-slate-400">
              <HelpCircle className="w-8 h-8 mx-auto stroke-1" />
              <p className="text-sm font-semibold">保存済みの要約が見つかりません</p>
              <p className="text-xs">フィルター条件を変更するか、新しく要約を生成して保存してください。</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-slate-100/70 border-b border-slate-200 text-[10px] uppercase font-bold text-slate-500 tracking-wider">
                    <th className="px-4 py-3">ファイル名 / ID</th>
                    <th className="px-3 py-3 text-center">ステータス</th>
                    <th className="px-3 py-3 text-right">アクション</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-xs">
                  {filteredSummaries.map((item) => {
                    const isSelected = item.id === selectedSummaryId;
                    return (
                      <tr 
                        key={item.id} 
                        onClick={() => setSelectedSummaryId(item.id)}
                        className={`cursor-pointer transition-colors ${isSelected ? "bg-indigo-50/70 hover:bg-indigo-50" : "hover:bg-slate-50/60"}`}
                      >
                        <td className="px-4 py-3 max-w-xs">
                          <div className="flex flex-col gap-0.5">
                            <span className="font-semibold text-slate-800 truncate" title={item.fileName}>
                              {item.fileName || "不明なファイル"}
                            </span>
                            <span className="text-[10px] text-slate-400 font-mono truncate select-all" title={item.fileId}>
                              ID: {item.fileId}
                            </span>
                            {item.parentId && (
                              <span className="text-[9px] text-indigo-600 font-bold bg-indigo-50 border border-indigo-100/50 px-1 py-0.2 rounded self-start mt-0.5">
                                📁 親: {item.parentId.slice(0, 8)}...
                              </span>
                            )}
                          </div>
                        </td>
                        <td className="px-3 py-3 text-center whitespace-nowrap">
                          {(() => {
                            switch (item.computedStatus) {
                              case "current":
                                return (
                                  <span className="inline-flex items-center gap-1 bg-emerald-50 text-emerald-700 text-[10px] px-2 py-0.5 rounded-full border border-emerald-200 font-bold">
                                    最新
                                  </span>
                                );
                              case "stale-schema":
                                return (
                                  <span className="inline-flex items-center gap-1 bg-amber-50 text-amber-700 text-[10px] px-2 py-0.5 rounded-full border border-amber-200 font-bold" title="スキーマが古いです">
                                    スキーマ古
                                  </span>
                                );
                              case "stale-prompt":
                                return (
                                  <span className="inline-flex items-center gap-1 bg-amber-50 text-amber-700 text-[10px] px-2 py-0.5 rounded-full border border-amber-200 font-bold" title="プロンプトが古いです">
                                    プロンプト古
                                  </span>
                                );
                              case "stale-file":
                                return (
                                  <span className="inline-flex items-center gap-1 bg-amber-50 text-amber-700 text-[10px] px-2 py-0.5 rounded-full border border-amber-200 font-bold" title="Google Drive側が更新されています">
                                    更新あり
                                  </span>
                                );
                              case "invalid":
                                return (
                                  <span className="inline-flex items-center gap-1 bg-rose-50 text-rose-700 text-[10px] px-2 py-0.5 rounded-full border border-rose-200 font-bold">
                                    無効
                                  </span>
                                );
                              default:
                                return (
                                  <span className="inline-flex items-center gap-1 bg-slate-100 text-slate-600 text-[10px] px-2 py-0.5 rounded-full border border-slate-200 font-bold">
                                    不明
                                  </span>
                                );
                            }
                          })()}
                        </td>
                        <td className="px-3 py-3 text-right" onClick={(e) => e.stopPropagation()}>
                          <button
                            onClick={() => handleSelectToTest(item)}
                            className="px-2 py-1 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 hover:text-indigo-800 font-bold rounded transition-colors text-[10px] inline-flex items-center gap-1 shadow-sm"
                          >
                            <Play className="w-2.5 h-2.5 text-indigo-600" />
                            検証
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Saved Metadata Detail display inspector (Part E) */}
        <div className="bg-white rounded-lg border border-slate-200 shadow-sm overflow-hidden lg:col-span-5 flex flex-col">
          <div className="px-5 py-4 border-b border-slate-200 bg-slate-50/50 flex items-center gap-2">
            <FileCode className="w-4 h-4 text-indigo-600" />
            <h4 className="font-semibold text-slate-800 text-sm">
              要約メタデータ詳細インスペクタ
            </h4>
          </div>

          {!selectedSummary ? (
            <div className="p-8 text-center text-slate-400 flex-1 flex flex-col items-center justify-center space-y-2">
              <HelpCircle className="w-8 h-8 stroke-1" />
              <p className="text-xs font-semibold">インスペクタに表示するファイルを選択</p>
              <p className="text-[11px]">左のテーブルから要約行をクリックすると、詳細なメタデータ、抽出フィールド、バリデーション状況、セーフコピーアクションが表示されます。</p>
            </div>
          ) : (
            <div className="p-5 space-y-5 divide-y divide-slate-100 max-h-[800px] overflow-y-auto">
              {/* Header Info */}
              <div className="space-y-2.5">
                <div className="flex items-start justify-between gap-2">
                  <div className="space-y-1">
                    <h5 className="font-bold text-slate-900 text-xs leading-tight">
                      {selectedSummary.fileName || "名称未設定ファイル"}
                    </h5>
                    <p className="text-[10px] text-slate-400 font-mono select-all">
                      File ID: {selectedSummary.fileId}
                    </p>
                  </div>
                  {/* Status Badge */}
                  {(() => {
                    switch (selectedSummary.computedStatus) {
                      case "current":
                        return (
                          <span className="shrink-0 inline-flex bg-emerald-50 text-emerald-700 text-[9px] px-2 py-0.5 rounded border border-emerald-200 font-extrabold uppercase">
                            Current
                          </span>
                        );
                      case "stale-schema":
                        return (
                          <span className="shrink-0 inline-flex bg-amber-50 text-amber-700 text-[9px] px-2 py-0.5 rounded border border-amber-200 font-extrabold uppercase">
                            Stale Schema
                          </span>
                        );
                      case "stale-prompt":
                        return (
                          <span className="shrink-0 inline-flex bg-amber-50 text-amber-700 text-[9px] px-2 py-0.5 rounded border border-amber-200 font-extrabold uppercase">
                            Stale Prompt
                          </span>
                        );
                      case "stale-file":
                        return (
                          <span className="shrink-0 inline-flex bg-amber-50 text-amber-700 text-[9px] px-2 py-0.5 rounded border border-amber-200 font-extrabold uppercase">
                            Stale File
                          </span>
                        );
                      case "invalid":
                        return (
                          <span className="shrink-0 inline-flex bg-rose-50 text-rose-700 text-[9px] px-2 py-0.5 rounded border border-rose-200 font-extrabold uppercase">
                            Invalid
                          </span>
                        );
                      default:
                        return (
                          <span className="shrink-0 inline-flex bg-slate-100 text-slate-600 text-[9px] px-2 py-0.5 rounded border border-slate-200 font-extrabold uppercase">
                            Unknown
                          </span>
                        );
                    }
                  })()}
                </div>

                {/* Status reasons (Part E) */}
                {selectedSummaryReasons.length > 0 && (
                  <div className="bg-rose-50 border border-rose-100 rounded p-2.5 space-y-1 text-[11px] text-rose-800">
                    <p className="font-bold flex items-center gap-1">
                      <AlertCircle className="w-3.5 h-3.5 text-rose-500 shrink-0" />
                      ステータス警告・異常理由:
                    </p>
                    <ul className="list-disc pl-4 space-y-0.5">
                      {selectedSummaryReasons.map((r, idx) => (
                        <li key={idx}>{r}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>

              {/* Action Buttons (Part E) */}
              <div className="pt-4 flex flex-wrap gap-2">
                <button
                  onClick={() => handleCopyJson(selectedSummary)}
                  className="px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded text-[10px] transition-all flex items-center gap-1.5 shadow-sm border border-slate-200"
                >
                  {copiedJsonId === selectedSummary.id ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3 text-slate-500" />}
                  {copiedJsonId === selectedSummary.id ? "安全JSONコピー済" : "安全JSONをコピー"}
                </button>

                <button
                  onClick={() => handleCopyOneLineSummary(selectedSummary)}
                  className="px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded text-[10px] transition-all flex items-center gap-1.5 shadow-sm border border-slate-200"
                >
                  {copiedOneLineId === selectedSummary.id ? <Check className="w-3 h-3 text-emerald-600" /> : <Clipboard className="w-3 h-3 text-slate-500" />}
                  {copiedOneLineId === selectedSummary.id ? "1行要約コピー済" : "1行要約をコピー"}
                </button>
              </div>

              {/* Core Metadata Fields (Part E) */}
              <div className="pt-4 space-y-2">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider font-mono block">システム基本メタデータ</span>
                
                <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-[11px]">
                  <div>
                    <span className="text-slate-400 block">親フォルダID (parentId)</span>
                    <span className="text-slate-800 font-mono break-all">{selectedSummary.parentId || "なし (ルート等)"}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">MimeType</span>
                    <span className="text-slate-800 font-mono">{selectedSummary.mimeType || "不明"}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">Drive更新日時 (modifiedTime)</span>
                    <span className="text-slate-800 font-mono">{selectedSummary.modifiedTime ? new Date(selectedSummary.modifiedTime).toLocaleString() : "不明"}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">要約生成日時 (generatedAt)</span>
                    <span className="text-slate-800 font-mono">{selectedSummary.generatedAt ? new Date(selectedSummary.generatedAt).toLocaleString() : "不明"}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">使用AIモデル</span>
                    <span className="text-slate-800 font-semibold text-indigo-950 bg-indigo-50 border border-indigo-100 rounded px-1.5 py-0.5">{selectedSummary.model || "不明"}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">スキーマバージョン</span>
                    <span className="text-slate-800 font-mono">{selectedSummary.schemaVersion || "不明"}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">プロンプトバージョン</span>
                    <span className="text-slate-800 font-mono">{selectedSummary.promptVersion || "不明"}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">システム指示バージョン</span>
                    <span className="text-slate-800 font-mono">{selectedSummary.systemInstructionVersion || "不明"}</span>
                  </div>
                </div>
              </div>

              {/* Extraction fields (Part E) */}
              <div className="pt-4 space-y-3 text-[11px]">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider font-mono block">要約・抽出構造化データ</span>

                {(() => {
                  const s = selectedSummary.structured;
                  const oneLine = s?.summary?.oneLine;
                  const docKinds = s?.documentKindInfo?.kinds?.map((k: any) => k.kind);
                  const primaryLang = s?.languageInfo?.primary;
                  
                  const subAreaStr = (s?.subjectAreas?.domains || [])
                    .map((d: any) => `${d.domain}: ${(d.labels || []).map((l: any) => l.label).join(", ")}`)
                    .join("\n");

                  return (
                    <>
                      <div>
                        <span className="text-slate-400 block font-bold">1行要約 (oneLineSummary)</span>
                        <p className="bg-slate-50 border border-slate-100 p-2 rounded text-slate-800 leading-relaxed mt-0.5 font-sans text-xs">
                          {oneLine || selectedSummary.summary || "情報なし"}
                        </p>
                      </div>

                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <span className="text-slate-400 block font-bold">ドキュメント分類</span>
                          <div className="flex flex-wrap gap-1 mt-0.5">
                            {docKinds && docKinds.length > 0 ? (
                              docKinds.map((t: string) => (
                                <span key={t} className="bg-slate-100 text-slate-700 px-1.5 py-0.5 rounded font-mono text-[10px] border border-slate-200">
                                  {t}
                                </span>
                              ))
                            ) : (
                              <span className="text-slate-400 italic">不明/指定なし</span>
                            )}
                          </div>
                        </div>

                        <div>
                          <span className="text-slate-400 block font-bold font-sans">主要言語</span>
                          <span className="text-slate-800 font-semibold block mt-0.5">{primaryLang || "不明"}</span>
                        </div>
                      </div>

                      <div>
                        <span className="text-slate-400 block font-bold">関連分野の概要 (subjectAreas)</span>
                        <p className="font-mono text-[10px] bg-indigo-50/50 border border-indigo-100/50 p-2 rounded text-indigo-950 block mt-0.5 leading-relaxed whitespace-pre-wrap">
                          {subAreaStr || "情報なし"}
                        </p>
                      </div>

                      <div className="grid grid-cols-2 gap-3 text-[10px] text-slate-500 font-mono">
                        <div>
                          <span>⚠️ 警告の数 (warnings)</span>
                          <span className="font-bold text-slate-800 ml-1.5">
                            {(s?.quality?.warnings?.length) || 0} 件
                          </span>
                        </div>
                        <div>
                          <span>🔗 外部参照数 (resourceReferences)</span>
                          <span className="font-bold text-slate-800 ml-1.5">
                            {(s?.indexing?.resourceReferences?.length) || 0} 件
                          </span>
                        </div>
                      </div>
                    </>
                  );
                })()}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
